import React, { createContext, useContext, useState, useEffect } from 'react';

const LANGS = {
  vi: {
    flag: '🇻🇳',
    label: 'VI',
    sb_sub: 'Hội viên doanh nghiệp',
    search_placeholder: 'Tìm kiếm...',
    menu_manage: 'Quản lý',
    menu_dashboard: 'Tổng quan',
    menu_members: 'Hội viên',
    menu_posts: 'Bài viết',
    menu_register: 'Đăng ký',
    menu_admin: 'Duyệt hội viên',
    menu_ai: 'Trợ lý AI',
    menu_system: 'Hệ thống',
    menu_settings: 'Cài đặt AI',
    lang_label: 'NGÔN NGỮ',
    stat_total_members: 'Tổng hội viên',
    stat_active: 'đang hoạt động',
    stat_pending: 'Chờ duyệt',
    stat_need_action: 'cần xử lý',
    stat_posts: 'Bài viết tháng này',
    stat_published: 'đã xuất bản',
    stat_events: 'Sự kiện sắp tới',
    stat_this_month: 'trong tháng này',
    section_new_members: 'Hội viên mới đăng ký',
    section_pending_posts: 'Bài chờ duyệt',
    btn_add: 'Thêm mới',
    notify_lang_switch: (n) => `Đã chuyển sang ${n}`,
    menu_directory: 'Danh mục đầy đủ',
    menu_tiers: 'Quyền lợi gói dịch vụ',
    menu_marketplace: 'Thị trường',
    menu_opportunities: 'Cơ hội giao thương',
    menu_national_feeds: 'Bảng tin toàn quốc',
    menu_events: 'Sự kiện',
    menu_guide: 'Hướng dẫn',
    menu_login: 'Đăng nhập',
    menu_logout: 'Đăng xuất',
    menu_welcome: 'Xin chào',
    hero_badge: 'Kết nối giao thương số 1 Việt Nam',
    hero_title: 'Kết nối doanh nghiệp, Cùng phát triển bền vững',
    hero_desc: 'AVG là cầu nối tin cậy giữa các doanh nghiệp hàng đầu. Tìm kiếm đối tác kinh doanh nhanh chóng, chia sẻ cơ hội đầu tư hợp tác và tiếp cận trợ lý AI nghiệp vụ thông minh 24/7.',
    hero_btn_register: 'Gia nhập ngay (Miễn phí)',
    hero_btn_explore: 'Khám phá hội viên',
    hero_realtime: 'Thời gian thực kết nối doanh nghiệp Việt',
    stat_active_members: 'Hội viên hoạt động',
    stat_verified_companies: 'Doanh nghiệp đã xác thực',
    stat_shared_opportunities: 'Cơ hội chia sẻ',
    stat_new_connections: 'Tin kết nối mới định kỳ',
    stat_diverse_companies: 'Doanh nghiệp đa dạng',
    stat_industries: 'Công nghệ, Sản xuất, Bán lẻ',
    stat_trade_events: 'Sự kiện giao thương',
    stat_annual_meetings: 'Hội nghị xúc tiến hàng năm',
    services_badge: 'Các dịch vụ chính',
    services_title: 'Giải pháp số hoá kết nối doanh nghiệp',
    services_desc: 'AVG cung cấp hạ tầng chuyển đổi số toàn diện để bạn giao thương, tìm đối tác và sử dụng Trợ lý AI phân tích sâu.',
    service_1_title: 'Kết nối Hội viên',
    service_1_desc: 'Kết nối hội viên, tiếp cận các doanh nghiệp lớn đã xác thực hồ sơ pháp nhân an toàn.',
    service_2_title: 'Bảng tin Cơ hội',
    service_2_desc: 'Tìm kiếm đối tác tiềm năng, bảng tin hội hỗ trợ kết nối dự án và cơ hội đầu tư hiệu quả.',
    service_3_title: 'Trợ lý AI thông minh',
    service_3_desc: 'Trợ lý AI nghiệp vụ trả lời thông tin tức thời, hỗ trợ tìm kiếm đối tác và đề xuất tự động.',
    service_4_title: 'Phân tích Thị trường',
    service_4_desc: 'Trợ lý AI thông minh phân tích xu hướng thị trường, tổng hợp dữ liệu giao dịch ngành.',
    featured_projects_title: 'Dự án kết nối nổi bật',
    featured_projects_desc: 'Tin đăng giao thương tiêu biểu được các hội viên đăng tải',
    btn_view_all_posts: 'Xem toàn bộ tin',
    featured_members_title: 'Hội viên nổi bật',
    featured_members_desc: 'Hội viên tiêu biểu được đề xuất hợp tác',
    btn_view_all_members: 'Xem danh mục hội viên',
    events_section_title: 'Giao lưu & Kết nối doanh nghiệp',
    events_section_desc: 'Các chương trình xúc tiến thương mại, hội thảo và gặp gỡ trực tiếp',
    btn_view_all_events: 'Xem tất cả sự kiện',
    pricing_section_title: 'Lựa chọn gói hội viên phù hợp',
    pricing_section_desc: 'Nâng cấp tài khoản để tiếp cận tệp đối tác rộng lớn hơn, đăng nhiều bài hơn và mở khóa quyền lợi AI đặc quyền.',
    tier_silver: 'Bạc',
    tier_gold: 'Vàng',
    tier_platinum: 'Bạch kim',
    price_free: 'Miễn phí',
    price_gold: '4.9 Mđ / năm',
    price_platinum: '9.9 Mđ / năm',
    btn_join_now: 'Gia nhập ngay',
    btn_upgrade_now: 'Đăng ký ngay',
    footer_desc: 'AVG là cầu nối tin cậy giữa các doanh nghiệp hàng đầu. Tìm kiếm đối tác kinh doanh nhanh chóng, chia sẻ cơ hội đầu tư, tự động kết nối doanh nghiệp Việt Nam 24/7.',
    footer_services: 'Dịch vụ',
    footer_support: 'Hỗ trợ',
    footer_contact: 'Liên hệ',
    footer_rights: '© Bảo lưu mọi quyền'
  },
  en: {
    flag: '🇺🇸',
    label: 'EN',
    sb_sub: 'Member Management',
    search_placeholder: 'Search...',
    menu_manage: 'Management',
    menu_dashboard: 'Dashboard',
    menu_members: 'Members',
    menu_posts: 'Posts',
    menu_register: 'Register',
    menu_admin: 'Approve Members',
    menu_ai: 'AI Assistant',
    menu_system: 'System',
    menu_settings: 'AI Settings',
    lang_label: 'LANGUAGE',
    stat_total_members: 'Total members',
    stat_active: 'active',
    stat_pending: 'Pending',
    stat_need_action: 'need review',
    stat_posts: 'Posts this month',
    stat_published: 'published',
    stat_events: 'Upcoming events',
    stat_this_month: 'this month',
    section_new_members: 'New registrations',
    section_pending_posts: 'Posts awaiting review',
    btn_add: 'Add new',
    notify_lang_switch: (n) => `Switched to ${n}`,
    menu_directory: 'Full Directory',
    menu_tiers: 'Membership Tiers',
    menu_marketplace: 'Marketplace',
    menu_opportunities: 'Trade Opportunities',
    menu_national_feeds: 'National Opportunity Feeds',
    menu_events: 'Events',
    menu_guide: 'Guide',
    menu_login: 'Login',
    menu_logout: 'Logout',
    menu_welcome: 'Welcome',
    hero_badge: 'No.1 Business Connection Platform in Vietnam',
    hero_title: 'Connecting Businesses, Growing Sustainably Together',
    hero_desc: 'AVG is a trusted bridge between leading businesses. Instantly search for trade partners, share co-investment opportunities, and access the smart 24/7 AI Business Assistant.',
    hero_btn_register: 'Join Now (Free)',
    hero_btn_explore: 'Explore Members',
    hero_realtime: 'Realtime connections for Vietnamese enterprises',
    stat_active_members: 'Active Members',
    stat_verified_companies: 'Verified Enterprises',
    stat_shared_opportunities: 'Shared Opportunities',
    stat_new_connections: 'Periodic matching feeds',
    stat_diverse_companies: 'Diverse Industries',
    stat_industries: 'Tech, Manufacturing, Retail',
    stat_trade_events: 'Trade Events',
    stat_annual_meetings: 'Annual promotional meetings',
    services_badge: 'Core Services',
    services_title: 'Digital Solutions for B2B Matching',
    services_desc: 'AVG provides comprehensive digital infrastructure to help you trade, discover partners, and leverage AI analysis.',
    service_1_title: 'Member Connections',
    service_1_desc: 'Interact with registered members and approach large, verified legal enterprises safely.',
    service_2_title: 'Opportunity Feed',
    service_2_desc: 'Find potential trade partners, search project needs, and explore investment opportunities.',
    service_3_title: 'Smart AI Assistant',
    service_3_desc: 'Get instant replies from our AI advisor, offering automated recommendations for partners.',
    service_4_title: 'Market Analysis',
    service_4_desc: 'Leverage smart AI to monitor market trends and summarize industry trade insights.',
    featured_projects_title: 'Featured Matchings',
    featured_projects_desc: 'Outstanding trade and business opportunities shared by members',
    btn_view_all_posts: 'View All Feeds',
    featured_members_title: 'Featured Members',
    featured_members_desc: 'Outstanding members recommended for collaboration',
    btn_view_all_members: 'View All Members',
    events_section_title: 'Networking & Connection Events',
    events_section_desc: 'Trade promotions, business forums, and in-person matchmaking conferences',
    btn_view_all_events: 'View All Events',
    pricing_section_title: 'Select a Fitting Membership Tier',
    pricing_section_desc: 'Upgrade your subscription to reach larger partner databases, publish unlimited feeds, and unlock premium AI features.',
    tier_silver: 'Silver',
    tier_gold: 'Gold',
    tier_platinum: 'Platinum',
    price_free: 'Free',
    price_gold: '4.9M VND / year',
    price_platinum: '9.9M VND / year',
    btn_join_now: 'Join Now',
    btn_upgrade_now: 'Subscribe Now',
    footer_desc: 'AVG is a trusted bridge between leading businesses. Find partners quickly, share investment opportunities, and connect automatic matchmaking 24/7.',
    footer_services: 'Services',
    footer_support: 'Support',
    footer_contact: 'Contact',
    footer_rights: '© All rights reserved'
  },
  zh: {
    flag: '🇨🇳',
    label: 'ZH',
    sb_sub: '会员管理',
    search_placeholder: '搜索...',
    menu_manage: '管理',
    menu_dashboard: '总览',
    menu_members: '会员',
    menu_posts: '文章',
    menu_register: '注册',
    menu_admin: '审核会员',
    menu_ai: 'AI助手',
    menu_system: '系统',
    menu_settings: 'AI设置',
    lang_label: '语言',
    stat_total_members: '总会员数',
    stat_active: '活跃',
    stat_pending: '待审核',
    stat_need_action: '需处理',
    stat_posts: '本月文章',
    stat_published: '已发布',
    stat_events: '即将举办',
    stat_this_month: '本月',
    section_new_members: '新注册会员',
    section_pending_posts: '待审文章',
    btn_add: '新增',
    notify_lang_switch: (n) => `已切换到${n}`,
    menu_directory: '全部名录',
    menu_tiers: '会员权益',
    menu_marketplace: '市场交易',
    menu_opportunities: '商业机会',
    menu_national_feeds: '全国看板',
    menu_events: '活动机会',
    menu_guide: '使用指南',
    menu_login: '登录',
    menu_logout: '退出',
    menu_welcome: '欢迎',
    hero_badge: '越南第一的企业对接平台',
    hero_title: '连接企业，携手共赢可持续发展',
    hero_desc: 'AVG是领先企业之间值得信赖的桥梁。快速搜索贸易伙伴，分享共同投资机会，并使用24/7智能AI业务助手。',
    hero_btn_register: '立即加入（免费）',
    hero_btn_explore: '探索会员',
    hero_realtime: '实时对接越南企业',
    stat_active_members: '活跃会员',
    stat_verified_companies: '已核验企业',
    stat_shared_opportunities: '共享商机',
    stat_new_connections: '定期发布的商业对接',
    stat_diverse_companies: '多元化行业',
    stat_industries: '科技、制造、零售',
    stat_trade_events: '贸易活动',
    stat_annual_meetings: '年度贸易推介会议',
    services_badge: '核心服务',
    services_title: 'B2B智能对接数字解决方案',
    services_desc: 'AVG提供全面的数字化基础架构，帮助您进行贸易、发现合作伙伴并利用AI分析。',
    service_1_title: '会员对接',
    service_1_desc: '与注册会员互动，安全地接触已验证的法人实体企业。',
    service_2_title: '商机看板',
    service_2_desc: '寻找潜在的贸易伙伴，搜索项目需求，并探索投资机会。',
    service_3_title: '智能AI助手',
    service_3_desc: '从我们的AI业务顾问那里获得即时答复，提供自动匹配的合作伙伴推荐。',
    service_4_title: '市场分析',
    service_4_desc: '利用智能AI监控市场趋势并总结行业贸易洞察。',
    featured_projects_title: '热门对接项目',
    featured_projects_desc: '会员发布的优秀贸易和商业机会',
    btn_view_all_posts: '查看全部看板',
    featured_members_title: '优秀会员',
    featured_members_desc: '推荐合作的杰出会员企业',
    btn_view_all_members: '查看会员名录',
    events_section_title: '商务交流与对接活动',
    events_section_desc: '贸易推介、商业论坛和线下对接会',
    btn_view_all_events: '查看全部活动',
    pricing_section_title: '选择合适的会员等级',
    pricing_section_desc: '升级您的会员级别，接触更庞大的合作伙伴数据库，发布无限看板并解锁高级AI功能。',
    tier_silver: '银牌',
    tier_gold: '金牌',
    tier_platinum: '白金牌',
    price_free: '免费',
    price_gold: '490万 越南盾 / 年',
    price_platinum: '990万 越南盾 / 年',
    btn_join_now: '立即加入',
    btn_upgrade_now: '立即订阅',
    footer_desc: 'AVG是领先企业之间值得信赖的桥梁。快速寻找合作伙伴，分享投资商机，并实现24/7自动对接。',
    footer_services: '服务',
    footer_support: '支持',
    footer_contact: '联系我们',
    footer_rights: '© 版权所有 保留所有权利'
  },
  ja: {
    flag: '🇯🇵',
    label: 'JA',
    sb_sub: '会員管理',
    search_placeholder: '検索...',
    menu_manage: '管理',
    menu_dashboard: 'ダッシュボード',
    menu_members: '会員',
    menu_posts: '投稿',
    menu_register: '登録',
    menu_admin: '会員承認',
    menu_ai: 'AIアシスタント',
    menu_system: 'システム',
    menu_settings: 'AI設定',
    lang_label: '言語',
    stat_total_members: '総会員数',
    stat_active: 'アクティブ',
    stat_pending: '承認待ち',
    stat_need_action: '要対応',
    stat_posts: '今月の投稿',
    stat_published: '公開済み',
    stat_events: '今後のイベント',
    stat_this_month: '今月',
    section_new_members: '新規会員',
    section_pending_posts: '承認待ち記事',
    btn_add: '新規追加',
    notify_lang_switch: (n) => `${n}に切り替えました`,
    menu_directory: 'フルディレクトリ',
    menu_tiers: '会員特典',
    menu_marketplace: 'マーケット',
    menu_opportunities: 'ビジネス機会',
    menu_national_feeds: '全国フィード',
    menu_events: 'イベント',
    menu_guide: 'ガイド',
    menu_login: 'ログイン',
    menu_logout: 'ログアウト',
    menu_welcome: 'ようこそ',
    hero_badge: 'ベトナムNo.1ビジネス・マッチング・プラットフォーム',
    hero_title: '企業を繋ぎ、共に持続可能な成長へ',
    hero_desc: 'AVGは大手企業間の信頼できる架け橋です。ビジネスパートナーを迅速に検索し、共同投資の機会を共有し、24時間年中無休のスマートAIアシスタントにアクセスします。',
    hero_btn_register: '今すぐ参加（無料）',
    hero_btn_explore: '会員を見つける',
    hero_realtime: 'ベトナム企業のリアルタイム・マッチング',
    stat_active_members: 'アクティブ会員',
    stat_verified_companies: '認証済み企業',
    stat_shared_opportunities: '共有案件',
    stat_new_connections: '定期的なマッチングフィード',
    stat_diverse_companies: '多様な業界',
    stat_industries: 'IT、製造、小売',
    stat_trade_events: 'ビジネスイベント',
    stat_annual_meetings: '年次プロモーション会議',
    services_badge: 'コアサービス',
    services_title: 'B2Bマッチングのデジタルソリューション',
    services_desc: 'AVGは、取引、パートナーの開拓、AI分析の活用を支援する包括적인デジタルインフラを提供します。',
    service_1_title: '会員接続',
    service_1_desc: '登録会員と交流し、認証済みの安全な法人企業にアプローチします。',
    service_2_title: '案件フィード',
    service_2_desc: '潜在的なパートナーを検索し、プロジェクトニーズを確認し、投資機会を探ります。',
    service_3_title: 'スマートAI助手',
    service_3_desc: 'AIアドバイザーから即座に回答を得て、最適なパートナーの自動提案を受けます。',
    service_4_title: '市場分析',
    service_4_desc: 'スマートAIを活用して市場動向を監視し、業界の取引動向を要約します。',
    featured_projects_title: '注目のマッチング案件',
    featured_projects_desc: '会員から共有された優れた取引およびビジネス案件',
    btn_view_all_posts: 'すべてのフィードを表示',
    featured_members_title: '注目の会員',
    featured_members_desc: 'コラボレーションに推奨される優れた会員企業',
    btn_view_all_members: '会員名録を表示',
    events_section_title: 'ネットワーキング＆マッチングイベント',
    events_section_desc: '貿易プロモーション、ビジネスフォーラム、対面式マッチング会議',
    btn_view_all_events: 'すべてのイベントを表示',
    pricing_section_title: '最適なメンバーシッププランを選択',
    pricing_section_desc: 'プランをアップグレードして、より大きなパートナーデータベースにアクセスし、無制限のフィードを公開し、プレミアムAI機能のロックを解除します。',
    tier_silver: 'シルバー',
    tier_gold: 'ゴールド',
    tier_platinum: 'プラチナ',
    price_free: '無料',
    price_gold: '490万 ドン / 年',
    price_platinum: '990万 ドン / 年',
    btn_join_now: '今すぐ登録',
    btn_upgrade_now: '今すぐ申し込む',
    footer_desc: 'AVGは大手企業間の信頼できる架け橋です。パートナーを素早く見つけ、投資機会を共有し、24時間365日の自動マッチングを接続します。',
    footer_services: 'サービス',
    footer_support: 'サポート',
    footer_contact: 'お問い合わせ',
    footer_rights: '© All rights reserved. 無断転載を禁じます'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('avg_lang') || 'vi';
  });

  const t = (key) => {
    const langObj = LANGS[currentLang] || LANGS.vi;
    const value = langObj[key] || LANGS.vi[key];
    if (typeof value === 'function') return value;
    return value || key;
  };

  const changeLang = (lang) => {
    if (LANGS[lang]) {
      setCurrentLang(lang);
      localStorage.setItem('avg_lang', lang);
    }
  };

  const getLangDetails = () => LANGS[currentLang] || LANGS.vi;

  return (
    <LanguageContext.Provider value={{ currentLang, t, changeLang, getLangDetails, LANGS }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => useContext(LanguageContext);
