import React, { createContext, useContext, useState, useEffect } from 'react';

const LANGS = {
  vi: {
    flag: '🇻🇳',
    label: 'VI',
    sb_sub: 'Hội viên doanh nghiệp',
    search_placeholder: 'Tìm kiếm...',
    menu_manage: 'Quản lý',
    menu_dashboard: 'Tổng quan',
    menu_members: 'Hội viên',
    menu_posts: 'Bài viết',
    menu_register: 'Đăng ký',
    menu_admin: 'Duyệt hội viên',
    menu_ai: 'Trợ lý AI',
    menu_system: 'Hệ thống',
    menu_settings: 'Cài đặt AI',
    lang_label: 'NGÔN NGỮ',
    stat_total_members: 'Tổng hội viên',
    stat_active: 'đang hoạt động',
    stat_pending: 'Chờ duyệt',
    stat_need_action: 'cần xử lý',
    stat_posts: 'Bài viết tháng này',
    stat_published: 'đã xuất bản',
    stat_events: 'Sự kiện sắp tới',
    stat_this_month: 'trong tháng này',
    section_new_members: 'Hội viên mới đăng ký',
    section_pending_posts: 'Bài chờ duyệt',
    btn_add: 'Thêm mới',
    notify_lang_switch: (n) => `Đã chuyển sang ${n}`,
    menu_directory: 'Danh mục đầy đủ',
    menu_tiers: 'Quyền lợi gói dịch vụ',
    menu_marketplace: 'Thị trường',
    menu_opportunities: 'Cơ hội giao thương',
    menu_national_feeds: 'Bảng tin toàn quốc',
    menu_events: 'Sự kiện',
    menu_guide: 'Hướng dẫn',
    menu_login: 'Đăng nhập',
    menu_logout: 'Đăng xuất',
    menu_welcome: 'Xin chào',
    hero_badge: 'Kết nối giao thương số 1 Việt Nam',
    hero_title: 'Kết nối doanh nghiệp, Cùng phát triển bền vững',
    hero_desc: 'Voma là cầu nối tin cậy giữa các doanh nghiệp hàng đầu. Tìm kiếm đối tác kinh doanh nhanh chóng, chia sẻ cơ hội đầu tư hợp tác và tiếp cận trợ lý AI nghiệp vụ thông minh 24/7.',
    hero_btn_register: 'Gia nhập ngay (Miễn phí)',
    hero_btn_explore: 'Khám phá hội viên',
    hero_realtime: 'Thời gian thực kết nối doanh nghiệp Việt',
    stat_active_members: 'Hội viên hoạt động',
    stat_verified_companies: 'Doanh nghiệp đã xác thực',
    stat_shared_opportunities: 'Cơ hội chia sẻ',
    stat_new_connections: 'Tin kết nối mới định kỳ',
    stat_diverse_companies: 'Doanh nghiệp đa dạng',
    stat_industries: 'Công nghệ, Sản xuất, Bán lẻ',
    stat_trade_events: 'Sự kiện giao thương',
    stat_annual_meetings: 'Hội nghị xúc tiến hàng năm',
    services_badge: 'Các dịch vụ chính',
    services_title: 'Giải pháp số hoá kết nối doanh nghiệp',
    services_desc: 'Voma cung cấp hạ tầng chuyển đổi số toàn diện để bạn giao thương, tìm đối tác và sử dụng Trợ lý AI phân tích sâu.',
    service_1_title: 'Kết nối Hội viên',
    service_1_desc: 'Kết nối hội viên, tiếp cận các doanh nghiệp lớn đã xác thực hồ sơ pháp nhân an toàn.',
    service_2_title: 'Bảng tin Cơ hội',
    service_2_desc: 'Tìm kiếm đối tác tiềm năng, bảng tin hội hỗ trợ kết nối dự án và cơ hội đầu tư hiệu quả.',
    service_3_title: 'Trợ lý AI thông minh',
    service_3_desc: 'Trợ lý AI nghiệp vụ trả lời thông tin tức thời, hỗ trợ tìm kiếm đối tác và đề xuất tự động.',
    service_4_title: 'Phân tích Thị trường',
    service_4_desc: 'Trợ lý AI thông minh phân tích xu hướng thị trường, tổng hợp dữ liệu giao dịch ngành.',
    featured_projects_title: 'Dự án kết nối nổi bật',
    featured_projects_desc: 'Tin đăng giao thương tiêu biểu được các hội viên đăng tải',
    btn_view_all_posts: 'Xem toàn bộ tin',
    featured_members_title: 'Hội viên nổi bật',
    featured_members_desc: 'Hội viên tiêu biểu được đề xuất hợp tác',
    btn_view_all_members: 'Xem danh mục hội viên',
    events_section_title: 'Giao lưu & Kết nối doanh nghiệp',
    events_section_desc: 'Các chương trình xúc tiến thương mại, hội thảo và gặp gỡ trực tiếp',
    btn_view_all_events: 'Xem tất cả sự kiện',
    pricing_section_title: 'Lựa chọn gói hội viên phù hợp',
    pricing_section_desc: 'Nâng cấp tài khoản để tiếp cận tệp đối tác rộng lớn hơn, đăng nhiều bài hơn và mở khóa quyền lợi AI đặc quyền.',
    tier_silver: 'Bạc',
    tier_gold: 'Vàng',
    tier_platinum: 'Bạch kim',
    price_free: 'Miễn phí',
    price_gold: '4.9 Mđ / năm',
    price_platinum: '9.9 Mđ / năm',
    btn_join_now: 'Gia nhập ngay',
    btn_upgrade_now: 'Đăng ký ngay',
    footer_desc: 'Voma là cầu nối tin cậy giữa các doanh nghiệp hàng đầu. Tìm kiếm đối tác kinh doanh nhanh chóng, chia sẻ cơ hội đầu tư, tự động kết nối doanh nghiệp Việt Nam 24/7.',
    footer_services: 'Dịch vụ',
    footer_support: 'Hỗ trợ',
    footer_contact: 'Liên hệ',
    footer_rights: '© Bảo lưu mọi quyền',
    label_popular: 'Phổ biến',
    label_elite: 'Thượng lưu',
    price_gold_val: '5.000.000đ',
    price_platinum_val: '15.000.000đ',
    pricing_per_year: 'năm',
    silver_feat_1: 'Hội viên hoạt động cơ bản',
    silver_feat_2: 'Hiển thị doanh nghiệp tại trang danh sách',
    silver_feat_3: 'Đăng tối đa 3 tin bài kết nối/tháng',
    silver_feat_4: 'Hỏi đáp Trợ lý AI cơ bản',
    gold_feat_1: 'Đầy đủ quyền lợi gói Silver',
    gold_feat_2: 'Ưu tiên hiển thị doanh nghiệp nổi bật',
    gold_feat_3: 'Đăng 15 tin bài kết nối/tháng',
    gold_feat_4: 'Mở rộng tương tác AI tự động kết nối',
    gold_feat_5: 'Nhận cơ hội giao thương đặc quyền',
    plat_feat_1: 'Quyền lợi cao cấp nhất hệ thống',
    plat_feat_2: 'Đăng tin giao thương không giới hạn',
    plat_feat_3: 'Tư vấn kết nối đối tác riêng biệt',
    plat_feat_4: 'Báo cáo phân tích thị trường chuyên sâu',
    plat_feat_5: 'Trợ lý AI riêng tùy biến cho thương hiệu',
    label_desc: 'Mô tả hoạt động',
    btn_read_more: 'Đọc bài viết',
    btn_read_post: 'Đọc bài',
    btn_view_details: 'Xem chi tiết',
    btn_back_to_feed: 'Quay lại Bảng tin',
    label_page: 'Trang',
    btn_back_prev: 'Trang trước',
    btn_go_next: 'Trang sau',
    label_show: 'Hiển thị',
    posts_title: 'Tin bài & Cơ hội giao thương',
    posts_subtitle: 'Cập nhật tin tức, cơ hội hợp tác kinh tế, tuyển dụng mới nhất từ các doanh nghiệp hội viên.',
    members_title: 'Thư mục doanh nghiệp hội viên',
    members_subtitle: 'Khám phá các doanh nghiệp thành viên đáng tin cậy trong mạng lưới Voma.',
    search_members_placeholder: 'Tìm tên, ngành, tỉnh thành...',
    search_posts_placeholder: 'Tìm bài viết, đối tác...',
    all_tiers: 'Tất cả hạng',
    all_industries: 'Tất cả ngành nghề',
    all_members: 'Tất cả hội viên',
    all_types: 'Tất cả phân loại',
    type_offer: 'Cung cấp sản phẩm',
    type_demand: 'Tìm kiếm / Nhu cầu',
    type_cooperate: 'Hợp tác phát triển',
    type_offer_short: 'Cung cấp',
    type_demand_short: 'Nhu cầu',
    type_cooperate_short: 'Hợp tác',
    posts_per_page: (count) => `${count} bài/trang`,
    members_per_page: (count) => `${count} thành viên`,
    found_members: (count) => `Tìm thấy ${count} hội viên`,
    found_posts: (count) => `Tìm thấy ${count} bài viết`,
    loading_posts: 'Đang tải bài viết...',
    loading_members: 'Đang tải danh sách hội viên...',
    no_posts_found: 'Không tìm thấy bài viết nào phù hợp với bộ lọc.',
    no_members_found: 'Không tìm thấy hội viên nào phù hợp với bộ lọc.',
    featured_members_header: 'Hội viên nổi bật được đề xuất',
    contact_login_required: 'Đăng nhập để hiển thị liên hệ',
    login_required_desc: 'Bạn cần đăng nhập để xem thông tin liên hệ trực tiếp của doanh nghiệp này.',
    login_now: 'Đăng nhập ngay',
    contact_info_label: 'Thông tin liên hệ',
    sidebar_author: 'ĐƠN VỊ ĐĂNG TẢI',
    location_default: 'Việt Nam',
    desc_default: 'Chưa có mô tả chi tiết hoạt động kinh doanh.',
    date_posted_label: 'Đăng ngày',
    category_default: 'Chung',
    badge_featured: 'Nổi bật',
    breadcrumb_home: 'Trang chủ',
    breadcrumb_opps: 'Bảng tin cơ hội',
    tier_platinum_partner: 'Đối tác Platinum',
    tier_platinum_members: 'Hội viên Platinum',
    tier_gold_members: 'Hội viên Gold',
    tier_silver_members: 'Hội viên Silver',
    translate_select_lang: 'Dịch sang',
    translate_button: 'Dịch nội dung (AI)',
    translate_view_original: 'Xem bản gốc (VI)',
    translate_view_original_short: 'Xem gốc',

    // VI Additions
    loading_latest_opps: 'Đang tải danh sách cơ hội giao thương mới nhất...',
    no_approved_opps: 'Hiện chưa có cơ hội giao thương nào được duyệt.',
    btn_contact: 'Liên hệ',
    loading_events_list: 'Đang tải danh sách sự kiện...',
    status_upcoming: 'Sắp diễn ra',
    status_ongoing: 'Đang diễn ra',
    status_completed: 'Đã kết thúc',
    status_cancelled: 'Đã hủy',
    login_required_location: 'Đăng nhập để xem chi tiết địa điểm.',
    no_upcoming_events: 'Hiện chưa có sự kiện giao thương nào sắp tới.',
    error_loading_events: 'Không thể tải danh sách sự kiện',
    login_required_event_confirm: 'Vui lòng đăng nhập để xem chi tiết địa điểm và thông tin mô tả sự kiện. Đến trang đăng nhập?',
    login_required_feature: 'Vui lòng đăng nhập để thực hiện tính năng này.',
    error_occurred: 'Có lỗi xảy ra.',
    events_title: 'Sự kiện giao thương & Kết nối',
    events_subtitle: 'Giao lưu trực tiếp, kết nối giao thương giữa các hội viên doanh nghiệp.',
    search_events_placeholder: 'Tìm kiếm sự kiện...',
    error_loading_events_prefix: 'Lỗi tải danh sách sự kiện:',
    no_events_found: 'Không tìm thấy sự kiện nào phù hợp.',
    event_details_title: 'Chi tiết sự kiện giao thương',
    label_event_name: 'Tên Sự Kiện',
    label_organizer: 'Đơn vị tổ chức',
    label_event_date: 'Ngày Tổ chức',
    label_max_capacity: 'Sức chứa tối đa',
    label_location: 'Địa điểm tổ chức',
    label_event_description: 'Mô tả chi tiết',
    no_event_desc: 'Không có mô tả chi tiết cho sự kiện này.',
    status_interested: 'Đã quan tâm',
    btn_interest: 'Quan tâm sự kiện',
    btn_close: 'Đóng',
    capacity_people: (count) => `${count} người`,
    capacity_unlimited: 'Không giới hạn',
    confirm_delete_session: 'Bạn có chắc chắn muốn xóa cuộc trò chuyện này?',
    error_ai_call: 'Có lỗi xảy ra khi gọi AI.',
    error_send_msg: 'Lỗi gửi tin nhắn',
    date_today: 'Hôm nay',
    date_yesterday: 'Hôm qua',
    login_ai_chat_title: 'Đăng nhập để sử dụng Trợ lý AI',
    login_ai_chat_desc: 'Tính năng Trợ lý AI chỉ dành cho hội viên doanh nghiệp đã đăng nhập và được phê duyệt. Vui lòng đăng nhập tài khoản hội viên của bạn.',
    register_new: 'Đăng ký mới',
    chat_history_title: 'Lịch sử trò chuyện',
    new_chat_btn_tooltip: 'Cuộc trò chuyện mới',
    search_chat_placeholder: 'Tìm kiếm hội thoại...',
    loading_chat_history: 'Đang tải lịch sử...',
    no_chat_history: 'Không có lịch sử trò chuyện.',
    new_chat_session_title: 'Cuộc trò chuyện mới',
    delete_chat_tooltip: 'Xóa hội thoại',
    label_topics: 'Chủ đề',
    topic_business: 'Kinh doanh',
    topic_investment: 'Đầu tư',
    topic_connection: 'Kết nối',
    ai_assistant_title: 'Trợ lý thông minh AI',
    status_online: 'Online',
    loading_messages: 'Đang tải tin nhắn...',
    ai_welcome_1: 'Xin chào! Tôi là Trợ lý AI phân tích doanh nghiệp của Voma.',
    ai_welcome_2: 'Tôi được tích hợp dữ liệu cơ sở thực của hội viên để hỗ trợ tra cứu hồ sơ năng lực, các cơ hội hợp tác và sự kiện. Bạn cần phân tích lĩnh vực nào hôm nay?',
    ai_suggestion_1_lbl: 'Phân tích thị trường B2B',
    ai_suggestion_1_val: 'Phân tích xu hiện trạng doanh nghiệp B2B năm 2026',
    ai_suggestion_2_lbl: 'Tìm đối tác Công nghệ',
    ai_suggestion_2_val: 'Tìm đối tác trong ngành Công nghệ thông tin',
    ai_suggestion_3_lbl: 'Sự kiện giao thương',
    ai_suggestion_3_val: 'Sự kiện kết nối giao lưu sắp tới',
    ai_thinking: 'Trợ lý AI đang suy nghĩ...',
    chat_input_placeholder: 'Nhập tin nhắn của bạn...',
    chat_help_tip: 'Nhấn Enter để gửi · Shift+Enter để xuống dòng',
    data_retrieval_label: 'Truy xuất dữ liệu',
    ai_config_title: 'Cấu hình AI',
    status_label: 'Trạng thái',
    premium_model_label: (tier) => `Mô hình cao cấp (Gói ${tier})`,
    system_default_model: '[Mặc định hệ thống]',
    free_model_desc: 'Mô hình hiện hành có khả năng tìm kiếm chéo hồ sơ doanh nghiệp và cơ hội giao thương B2B toàn hệ thống.',
    upgrade_to_change_models: 'Nâng cấp gói Gold/Platinum để tự do đổi mô hình AI khác (OpenAI, Claude, Grok, DeepSeek...)',
    suggested_actions_title: 'Hành động đề xuất',
    suggested_action_1_title: 'Kết nối B2B',
    suggested_action_1_desc: 'Yêu cầu giới thiệu và thông tin liên hệ',
    suggested_action_2_title: 'Tham gia sự kiện',
    suggested_action_2_desc: 'Xúc tiến kết nối giao thương trực tiếp',
    suggested_action_3_title: 'Cơ hội đầu tư',
    suggested_action_3_desc: 'Trợ lý phân tích dự báo giao thương',
    profile_update_success: 'Đã cập nhật thông tin doanh nghiệp thành công!',
    upgrade_confirm_msg: (tier) => `Bạn muốn gửi yêu cầu nâng cấp tài khoản lên gói ${tier}?`,
    upgrade_request_success: 'Gửi yêu cầu nâng cấp thành công! Vui lòng chờ admin phê duyệt.',
    upgrade_request_fail: 'Yêu cầu nâng cấp thất bại.',
    delete_post_confirm: (title) => `Bạn có chắc chắn muốn xóa bài đăng "${title}"?`,
    delete_post_success: 'Đã xóa bài đăng thành công!',
    error_load_post: 'Không thể tải chi tiết bài viết.',
    alert_enter_title: 'Vui lòng nhập tiêu đề bài đăng',
    alert_enter_body: 'Vui lòng nhập nội dung chi tiết bài đăng',
    alert_enter_contact: 'Vui lòng cung cấp thông tin liên hệ trực tiếp',
    save_draft_success: 'Đã lưu bản nháp thành công!',
    publish_post_success: 'Đã đăng tin thành công! Tin đăng đang chờ Admin duyệt.',
    loading_dashboard: 'Đang tải dữ liệu Dashboard...',
    dashboard_title: 'Dashboard Hội viên',
    tier_expiry_label: 'Hạn dùng gói',
    pending_upgrade_status: (tier) => `Chờ duyệt nâng cấp lên ${tier}`,
    manage_account_desc: (name) => `Quản trị tài khoản doanh nghiệp thành viên ${name}`,
    btn_create_new_post: 'Đăng tin giao thương mới',
    pending_account_status_title: 'Tài khoản đang chờ duyệt',
    pending_account_status_desc: 'Hồ sơ doanh nghiệp đang được admin kiểm tra. Các chức năng đăng bài và AI Chat sẽ hoạt động sau khi được phê duyệt.',
    approved_account_status_title: 'Hội viên chính thức',
    approved_account_status_desc: 'Tài khoản của bạn đã được phê duyệt. Bạn đã được cấp toàn quyền giao dịch và sử dụng Trợ lý AI.',
    rejected_account_status_title: 'Hồ sơ bị từ chối',
    rejected_account_status_desc: 'Doanh nghiệp chưa đạt yêu cầu kiểm duyệt. Vui lòng cập nhật lại hồ sơ chi tiết.',
    update_profile_title: 'Cập nhật hồ sơ doanh nghiệp',
    label_company_name: 'Tên Doanh nghiệp',
    label_tax_code: 'Mã số thuế',
    label_business_license: 'Giấy phép KD',
    label_industry: 'Ngành nghề',
    label_employee_scale: 'Quy mô nhân sự',
    label_address: 'Địa chỉ',
    label_city: 'Tỉnh/Thành phố',
    label_social_media: 'Mạng xã hội (Fanpage / LinkedIn)',
    label_contact_person: 'Tên người liên hệ',
    label_contact_position: 'Chức vụ người liên hệ',
    label_phone_number: 'Số điện thoại',
    label_joining_goal: 'Mục tiêu tham gia',
    label_short_description: 'Mô tả ngắn hoạt động',
    label_reset_password_desc: 'Thiết lập lại Mật khẩu mới (Bỏ trống nếu không đổi)',
    placeholder_password_min_8: 'Mật khẩu tối thiểu 8 ký tự...',
    btn_saving: 'Đang lưu...',
    btn_save_profile: 'Lưu hồ sơ',
    upgrade_tier_title: 'Nâng cấp gói thành viên',
    upgrade_tier_desc: 'Nâng cấp lên gói Gold hoặc Platinum để đăng tin giao thương không giới hạn và tăng hiệu suất AI.',
    upgrade_request_pending_prefix: 'Yêu cầu nâng cấp đang chờ duyệt',
    btn_upgrade_gold: 'Lên Gold',
    btn_upgrade_platinum: 'Lên Platinum',
    posts_stats_title: 'Thống kê tin đăng',
    stat_total_posts: 'Tin bài',
    stat_approved_posts: 'Đã duyệt',
    stat_total_views: 'Lượt xem',
    my_published_posts_title: 'Tin bài đã đăng của bạn',
    no_posts_published: 'Bạn chưa đăng tin bài cơ hội giao thương nào.',
    btn_edit: 'Sửa',
    btn_delete: 'Xóa',
    modal_create_post_title: 'Đăng tin cơ hội giao thương mới',
    modal_edit_post_title: 'Cập nhật tin đăng',
    modal_post_title_label: 'Tiêu đề bài đăng',
    modal_post_title_placeholder: 'Ví dụ: Cần tìm nhà cung cấp hạt điều xuất khẩu...',
    modal_post_type_label: 'Loại tin bài',
    type_find_partner: 'Tìm kiếm đối tác',
    type_buy_sell: 'Cần mua / Cần bán',
    type_event_announcement: 'Thông báo sự kiện',
    type_recruitment: 'Tuyển dụng',
    modal_post_category_label: 'Danh mục ngành',
    modal_post_category_placeholder: 'Ví dụ: Nông nghiệp, CNTT...',
    modal_post_tags_label: 'Tags từ khoá (phân tách bằng dấu phẩy)',
    modal_post_tags_placeholder: 'Ví dụ: nông sản, xuất khẩu, b2b',
    modal_post_summary_label: 'Tóm tắt bài đăng',
    modal_post_summary_placeholder: 'Tóm tắt ngắn gọn nhu cầu trong 1-2 câu...',
    modal_post_body_label: 'Nội dung chi tiết cơ hội giao thương',
    modal_post_contact_label: 'Thông tin liên hệ trực tiếp',
    modal_post_contact_placeholder: 'Ví dụ: email@vinatech.vn | 0901 111 222 (Mr. Đức)',
    modal_post_deadline_label: 'Hạn liên hệ (Hạn đăng bài)',
    modal_post_image_label: 'Ảnh minh họa',
    modal_post_image_placeholder: 'Dán link ảnh hoặc chọn tệp tải lên...',
    btn_choose_file: 'Chọn tệp',
    status_uploading_image: 'Đang tải ảnh lên...',
    modal_request_featured_label: 'Yêu cầu ghim nổi bật bài đăng này ngoài trang chủ (Quyền lợi Platinum)',
    btn_cancel: 'Hủy',
    btn_save_draft: 'Lưu nháp',
    btn_sending: 'Đang gửi...',
    btn_update_publish: 'Cập nhật & Đăng',
    btn_publish: 'Đăng tin',
    err_fill_company_name: 'Vui lòng điền tên doanh nghiệp',
    err_select_industry: 'Vui lòng chọn lĩnh vực hoạt động',
    err_select_scale: 'Vui lòng chọn quy mô nhân sự',
    err_image_size: 'Vui lòng chọn file ảnh nhỏ hơn 2MB.',
    err_fill_tax_code: 'Vui lòng điền mã số thuế',
    err_select_city: 'Vui lòng chọn tỉnh thành',
    err_fill_address: 'Vui lòng điền địa chỉ chi tiết',
    err_fill_description: 'Vui lòng điền mô tả ngắn hoạt động kinh doanh',
    err_fill_rep_name: 'Vui lòng điền tên người đại diện',
    err_fill_rep_position: 'Vui lòng điền chức vụ người đại diện',
    err_fill_email: 'Vui lòng điền email liên hệ',
    err_fill_phone: 'Vui lòng điền số điện thoại',
    err_fill_password: 'Vui lòng thiết lập mật khẩu',
    err_password_min_8: 'Mật khẩu phải tối thiểu 8 ký tự',
    register_sidebar_circular_text: 'Voma — MỞ RỘNG MẠNG LƯỚI, TỐI ĐA HÓA CƠ HỘI. KẾT NỐI TOÀN CẦU, PHÁT TRIỂN BỀN VỮNG.',
    register_sidebar_desc: 'Khởi tạo doanh nghiệp, xây dựng hồ sơ uy tín và mở rộng mạng lưới giao lưu kinh doanh rộng khắp toàn quốc.',
    register_card_title: 'Gia nhập Voma',
    step_company: 'Doanh nghiệp',
    step_representative: 'Người đại diện',
    step_account: 'Tài khoản',
    step_1_title: '1. Kê khai thông tin doanh nghiệp',
    step_2_title: '2. Thông tin người đại diện giao thương',
    step_3_title: '3. Thiết lập tài khoản bảo mật & gói hội viên',
    placeholder_company_name: 'Ví dụ: Công ty Cổ phần Công nghệ Vina Tech',
    label_website: 'Địa chỉ Website doanh nghiệp',
    placeholder_website: 'Ví dụ: https://vinatech.vn',
    placeholder_industry: 'Chọn hoặc tự điền lĩnh vực...',
    placeholder_select_scale: '-- Chọn quy mô --',
    scale_under_10: 'Dưới 10 người',
    scale_10_50: '10 – 50 người',
    scale_50_200: '50 – 200 người',
    scale_200_500: '200 – 500 người',
    scale_over_500: 'Trên 500 người',
    placeholder_tax_code: 'Mã số thuế gồm 10 chữ số',
    placeholder_city: 'Chọn hoặc tự điền tỉnh thành...',
    placeholder_address: 'Ví dụ: 45 Lý Thường Kiệt, Hoàn Kiếm, Hà Nội',
    label_zip: 'Mã Bưu điện (ZIP code)',
    placeholder_zip: 'Ví dụ: 100000',
    placeholder_social: 'facebook.com/company',
    placeholder_short_description: 'Giới thiệu sơ lược sản phẩm, dịch vụ...',
    btn_continue: 'Tiếp tục',
    btn_back: 'Quay lại',
    placeholder_rep_name: 'Họ và tên người liên hệ',
    placeholder_rep_position: 'Ví dụ: Giám đốc kinh doanh',
    placeholder_rep_email: 'email@company.vn',
    placeholder_rep_phone: 'Số điện thoại di động',
    placeholder_joining_goal: 'Ví dụ: Tìm đối tác xuất khẩu nông sản sang Nhật',
    label_referral: 'Biết tới Voma qua kênh nào?',
    placeholder_referral: '-- Chọn kênh giới thiệu --',
    label_login_email: 'Email đăng nhập (Username)',
    login_email_help_text: 'Voma sử dụng Email doanh nghiệp ở Bước 2 làm tên đăng nhập tài khoản.',
    label_setup_password: 'Thiết lập Mật khẩu',
    placeholder_setup_password: 'Mật khẩu chứa tối thiểu 8 ký tự',
    label_choose_tier: 'Chọn Gói dịch vụ gia nhập',
    btn_register: 'Đăng ký ngay',
    btn_registering: 'Đang đăng ký...',
    register_success_title: 'Đăng ký hồ sơ thành công!',
    register_success_desc: (name, email) => `Hồ sơ doanh nghiệp ${name} đã được lưu trữ trên hệ thống Voma AI và đang chờ quản trị viên phê duyệt. Chúng tôi sẽ liên hệ sớm qua email ${email}.`,
    btn_back_home: 'Quay lại Trang chủ',
    status_approved: 'Đã duyệt',
    status_rejected: 'Từ chối',
    status_draft: 'Bản nháp',
    status_pending: 'Chờ duyệt'
  },
  en: {
    flag: '🇺🇸',
    label: 'EN',
    sb_sub: 'Member Management',
    search_placeholder: 'Search...',
    menu_manage: 'Management',
    menu_dashboard: 'Dashboard',
    menu_members: 'Members',
    menu_posts: 'Posts',
    menu_register: 'Register',
    menu_admin: 'Approve Members',
    menu_ai: 'AI Assistant',
    menu_system: 'System',
    menu_settings: 'AI Settings',
    lang_label: 'LANGUAGE',
    stat_total_members: 'Total members',
    stat_active: 'active',
    stat_pending: 'Pending',
    stat_need_action: 'need review',
    stat_posts: 'Posts this month',
    stat_published: 'published',
    stat_events: 'Upcoming events',
    stat_this_month: 'this month',
    section_new_members: 'New registrations',
    section_pending_posts: 'Posts awaiting review',
    btn_add: 'Add new',
    notify_lang_switch: (n) => `Switched to ${n}`,
    menu_directory: 'Full Directory',
    menu_tiers: 'Membership Tiers',
    menu_marketplace: 'Marketplace',
    menu_opportunities: 'Trade Opportunities',
    menu_national_feeds: 'National Opportunity Feeds',
    menu_events: 'Events',
    menu_guide: 'Guide',
    menu_login: 'Login',
    menu_logout: 'Logout',
    menu_welcome: 'Welcome',
    hero_badge: 'No.1 Business Connection Platform in Vietnam',
    hero_title: 'Connecting Businesses, Growing Sustainably Together',
    hero_desc: 'Voma is a trusted bridge between leading businesses. Instantly search for trade partners, share co-investment opportunities, and access the smart 24/7 AI Business Assistant.',
    hero_btn_register: 'Join Now (Free)',
    hero_btn_explore: 'Explore Members',
    hero_realtime: 'Realtime connections for Vietnamese enterprises',
    stat_active_members: 'Active Members',
    stat_verified_companies: 'Verified Enterprises',
    stat_shared_opportunities: 'Shared Opportunities',
    stat_new_connections: 'Periodic matching feeds',
    stat_diverse_companies: 'Diverse Industries',
    stat_industries: 'Tech, Manufacturing, Retail',
    stat_trade_events: 'Trade Events',
    stat_annual_meetings: 'Annual promotional meetings',
    services_badge: 'Core Services',
    services_title: 'Digital Solutions for B2B Matching',
    services_desc: 'Voma provides comprehensive digital infrastructure to help you trade, discover partners, and leverage AI analysis.',
    service_1_title: 'Member Connections',
    service_1_desc: 'Interact with registered members and approach large, verified legal enterprises safely.',
    service_2_title: 'Opportunity Feed',
    service_2_desc: 'Find potential trade partners, search project needs, and explore investment opportunities.',
    service_3_title: 'Smart AI Assistant',
    service_3_desc: 'Get instant replies from our AI advisor, offering automated recommendations for partners.',
    service_4_title: 'Market Analysis',
    service_4_desc: 'Leverage smart AI to monitor market trends and summarize industry trade insights.',
    featured_projects_title: 'Featured Matchings',
    featured_projects_desc: 'Outstanding trade and business opportunities shared by members',
    btn_view_all_posts: 'View All Feeds',
    featured_members_title: 'Featured Members',
    featured_members_desc: 'Outstanding members recommended for collaboration',
    btn_view_all_members: 'View All Members',
    events_section_title: 'Networking & Connection Events',
    events_section_desc: 'Trade promotions, business forums, and in-person matchmaking conferences',
    btn_view_all_events: 'View All Events',
    pricing_section_title: 'Select a Fitting Membership Tier',
    pricing_section_desc: 'Upgrade your subscription to reach larger partner databases, publish unlimited feeds, and unlock premium AI features.',
    tier_silver: 'Silver',
    tier_gold: 'Gold',
    tier_platinum: 'Platinum',
    price_free: 'Free',
    price_gold: '4.9M VND / year',
    price_platinum: '9.9M VND / year',
    btn_join_now: 'Join Now',
    btn_upgrade_now: 'Subscribe Now',
    footer_desc: 'Voma is a trusted bridge between leading businesses. Find partners quickly, share investment opportunities, and connect automatic matchmaking 24/7.',
    footer_services: 'Services',
    footer_support: 'Support',
    footer_contact: 'Contact',
    footer_rights: '© All rights reserved',
    label_popular: 'Popular',
    label_elite: 'Elite',
    price_gold_val: '$200',
    price_platinum_val: '$600',
    pricing_per_year: 'year',
    silver_feat_1: 'Basic membership access',
    silver_feat_2: 'Standard placement on member directory',
    silver_feat_3: 'Publish up to 3 matching posts / month',
    silver_feat_4: 'Standard AI Assistant Q&A access',
    gold_feat_1: 'All benefits of Silver tier included',
    gold_feat_2: 'Priority placement in featured directory',
    gold_feat_3: 'Publish up to 15 matching posts / month',
    gold_feat_4: 'Interactive AI matching automation',
    gold_feat_5: 'Access exclusive premium opportunities',
    plat_feat_1: 'Highest system access priority',
    plat_feat_2: 'Publish unlimited trade opportunities',
    plat_feat_3: 'Dedicated partner matching consulting',
    plat_feat_4: 'In-depth market research reports',
    plat_feat_5: 'Custom, brand-specific AI assistant',
    label_desc: 'Business Description',
    btn_read_more: 'Read post',
    btn_read_post: 'Read',
    btn_view_details: 'View details',
    btn_back_to_feed: 'Back to Feed',
    label_page: 'Page',
    btn_back_prev: 'Previous',
    btn_go_next: 'Next',
    label_show: 'Show',
    posts_title: 'Posts & Trade Opportunities',
    posts_subtitle: 'Get the latest news, trade opportunities, and recruitments from member enterprises.',
    members_title: 'Member Directory',
    members_subtitle: 'Explore trusted member businesses in the Voma network.',
    search_members_placeholder: 'Search by name, industry, city...',
    search_posts_placeholder: 'Search posts, partners...',
    all_tiers: 'All Tiers',
    all_industries: 'All Industries',
    all_members: 'All Members',
    all_types: 'All Types',
    type_offer: 'Offer / Provide',
    type_demand: 'Demand / Request',
    type_cooperate: 'Cooperation',
    type_offer_short: 'Offer',
    type_demand_short: 'Demand',
    type_cooperate_short: 'Cooperate',
    posts_per_page: (count) => `${count} posts/page`,
    members_per_page: (count) => `${count} members`,
    found_members: (count) => `Found ${count} members`,
    found_posts: (count) => `Found ${count} posts`,
    loading_posts: 'Loading posts...',
    loading_members: 'Loading members...',
    no_posts_found: 'No posts matching filters found.',
    no_members_found: 'No members matching filters found.',
    featured_members_header: 'Recommended Featured Members',
    contact_login_required: 'Login to display contact',
    login_required_desc: 'You need to log in to view the direct contact information of this business.',
    login_now: 'Login now',
    contact_info_label: 'Contact Information',
    sidebar_author: 'AUTHOR / PUBLISHER',
    location_default: 'Vietnam',
    desc_default: 'No business description provided.',
    date_posted_label: 'Posted date',
    category_default: 'General',
    badge_featured: 'Featured',
    breadcrumb_home: 'Home',
    breadcrumb_opps: 'Opportunity Feed',
    tier_platinum_partner: 'Platinum Partner',
    tier_platinum_members: 'Platinum Members',
    tier_gold_members: 'Gold Members',
    tier_silver_members: 'Silver Members',
    translate_select_lang: 'Translate to',
    translate_button: 'Translate (AI)',
    translate_view_original: 'View original (VI)',
    translate_view_original_short: 'View original',

    // EN Additions
    loading_latest_opps: 'Loading latest trade opportunities...',
    no_approved_opps: 'No approved opportunities found.',
    btn_contact: 'Contact',
    loading_events_list: 'Loading events...',
    status_upcoming: 'Upcoming',
    status_ongoing: 'Ongoing',
    status_completed: 'Completed',
    status_cancelled: 'Cancelled',
    login_required_location: 'Login to view location detail.',
    no_upcoming_events: 'No upcoming trade events available.',
    error_loading_events: 'Unable to load events',
    login_required_event_confirm: 'Please log in to view location details and description. Go to login page?',
    login_required_feature: 'Please log in to use this feature.',
    error_occurred: 'An error occurred.',
    events_title: 'Trade Events & Connection',
    events_subtitle: 'Networking and direct business matching between member companies.',
    search_events_placeholder: 'Search events...',
    error_loading_events_prefix: 'Error loading events list:',
    no_events_found: 'No matching events found.',
    event_details_title: 'Trade Event Details',
    label_event_name: 'Event Name',
    label_organizer: 'Organizer',
    label_event_date: 'Event Date',
    label_max_capacity: 'Max Capacity',
    label_location: 'Event Location',
    label_event_description: 'Detailed Description',
    no_event_desc: 'No detailed description for this event.',
    status_interested: 'Interested',
    btn_interest: 'Join Event',
    btn_close: 'Close',
    capacity_people: (count) => `${count} people`,
    capacity_unlimited: 'Unlimited',
    confirm_delete_session: 'Are you sure you want to delete this conversation?',
    error_ai_call: 'Error occurred during AI call.',
    error_send_msg: 'Failed to send message',
    date_today: 'Today',
    date_yesterday: 'Yesterday',
    login_ai_chat_title: 'Login to use AI Assistant',
    login_ai_chat_desc: 'The AI Assistant is only available for logged-in and approved member businesses. Please log in to your account.',
    register_new: 'Register',
    chat_history_title: 'Chat History',
    new_chat_btn_tooltip: 'New chat session',
    search_chat_placeholder: 'Search chats...',
    loading_chat_history: 'Loading chat history...',
    no_chat_history: 'No chat history found.',
    new_chat_session_title: 'New Chat Session',
    delete_chat_tooltip: 'Delete Chat',
    label_topics: 'Topics',
    topic_business: 'Business',
    topic_investment: 'Investment',
    topic_connection: 'Connection',
    ai_assistant_title: 'AI Smart Assistant',
    status_online: 'Online',
    loading_messages: 'Loading messages...',
    ai_welcome_1: 'Hello! I am the AI Business Analysis Assistant for Voma.',
    ai_welcome_2: 'I have access to member profiles to help you find capabilities, trade opportunities, and events. What area should we analyze today?',
    ai_suggestion_1_lbl: 'B2B Market Analysis',
    ai_suggestion_1_val: 'Analyze the state of B2B enterprises in 2026',
    ai_suggestion_2_lbl: 'Find Tech Partners',
    ai_suggestion_2_val: 'Search for partners in the IT industry',
    ai_suggestion_3_lbl: 'Trade Events',
    ai_suggestion_3_val: 'List upcoming trade networking events',
    ai_thinking: 'AI Assistant is thinking...',
    chat_input_placeholder: 'Type your message...',
    chat_help_tip: 'Press Enter to send · Shift+Enter for new line',
    data_retrieval_label: 'Data Retrieval',
    ai_config_title: 'AI Configurations',
    status_label: 'Status',
    premium_model_label: (tier) => `Premium Model (Tier ${tier})`,
    system_default_model: '[System Default]',
    free_model_desc: 'The current model can search across all enterprise profiles and B2B trade opportunities.',
    upgrade_to_change_models: 'Upgrade to Gold/Platinum to switch to other AI models (OpenAI, Claude, DeepSeek...)',
    suggested_actions_title: 'Suggested Actions',
    suggested_action_1_title: 'B2B Matchmaking',
    suggested_action_1_desc: 'Request introduction and contact details',
    suggested_action_2_title: 'Attend Event',
    suggested_action_2_desc: 'Promote direct trade networking',
    suggested_action_3_title: 'Investment Opportunity',
    suggested_action_3_desc: 'AI assistant forecasts and analysis',
    profile_update_success: 'Enterprise profile updated successfully!',
    upgrade_confirm_msg: (tier) => `Would you like to request an upgrade to ${tier}?`,
    upgrade_request_success: 'Upgrade request sent successfully! Awaiting admin approval.',
    upgrade_request_fail: 'Failed to request upgrade.',
    delete_post_confirm: (title) => `Are you sure you want to delete post "${title}"?`,
    delete_post_success: 'Post deleted successfully!',
    error_load_post: 'Failed to load post details.',
    alert_enter_title: 'Please enter a post title',
    alert_enter_body: 'Please enter detailed post content',
    alert_enter_contact: 'Please provide direct contact information',
    save_draft_success: 'Draft saved successfully!',
    publish_post_success: 'Post published successfully! Awaiting Admin approval.',
    loading_dashboard: 'Loading Dashboard data...',
    dashboard_title: 'Member Dashboard',
    tier_expiry_label: 'Expiry date',
    pending_upgrade_status: (tier) => `Pending upgrade to ${tier}`,
    manage_account_desc: (name) => `Manage account for member enterprise ${name}`,
    btn_create_new_post: 'Post New Opportunity',
    pending_account_status_title: 'Account Awaiting Approval',
    pending_account_status_desc: 'Your business profile is being reviewed by the admin. Posting and AI chat functions will be active once approved.',
    approved_account_status_title: 'Verified Member',
    approved_account_status_desc: 'Your account has been approved. You have full trading privileges and access to the AI Assistant.',
    rejected_account_status_title: 'Profile Rejected',
    rejected_account_status_desc: 'Your profile has not met approval criteria. Please update your profile details.',
    update_profile_title: 'Update Business Profile',
    label_company_name: 'Company Name',
    label_tax_code: 'Tax Code',
    label_business_license: 'Business License',
    label_industry: 'Industry',
    label_employee_scale: 'Company Size',
    label_address: 'Address',
    label_city: 'City / Province',
    label_social_media: 'Social Media (Fanpage / LinkedIn)',
    label_contact_person: 'Contact Name',
    label_contact_position: 'Contact Position',
    label_phone_number: 'Phone Number',
    label_joining_goal: 'Goal',
    label_short_description: 'Short Description',
    label_reset_password_desc: 'Reset Password (Leave blank to keep current)',
    placeholder_password_min_8: 'Minimum 8 characters...',
    btn_saving: 'Saving...',
    btn_save_profile: 'Save Profile',
    upgrade_tier_title: 'Upgrade Membership Tier',
    upgrade_tier_desc: 'Upgrade to Gold or Platinum to post unlimited opportunities and increase AI performance.',
    upgrade_request_pending_prefix: 'Upgrade request pending approval',
    btn_upgrade_gold: 'Upgrade Gold',
    btn_upgrade_platinum: 'Upgrade Platinum',
    posts_stats_title: 'Post Statistics',
    stat_total_posts: 'Total Posts',
    stat_approved_posts: 'Approved',
    stat_total_views: 'Views',
    my_published_posts_title: 'Your Published Opportunities',
    no_posts_published: 'You have not published any opportunities yet.',
    btn_edit: 'Edit',
    btn_delete: 'Delete',
    modal_create_post_title: 'Post New Trade Opportunity',
    modal_edit_post_title: 'Edit Post Details',
    modal_post_title_label: 'Post Title',
    modal_post_title_placeholder: 'Example: Looking for cashew exporter suppliers...',
    modal_post_type_label: 'Post Type',
    type_find_partner: 'Find Partner',
    type_buy_sell: 'Buy / Sell',
    type_event_announcement: 'Event Announcement',
    type_recruitment: 'Recruitment',
    modal_post_category_label: 'Category',
    modal_post_category_placeholder: 'Example: Agriculture, IT...',
    modal_post_tags_label: 'Tags (separated by commas)',
    modal_post_tags_placeholder: 'Example: agriculture, export, b2b',
    modal_post_summary_label: 'Short Summary',
    modal_post_summary_placeholder: 'Brief summary of your request in 1-2 sentences...',
    modal_post_body_label: 'Detailed Content',
    modal_post_contact_label: 'Direct Contact Details',
    modal_post_contact_placeholder: 'Example: email@vinatech.vn | 0901 111 222 (Mr. Duck)',
    modal_post_deadline_label: 'Deadline (Expiration)',
    modal_post_image_label: 'Cover Image',
    modal_post_image_placeholder: 'Paste image link or upload a file...',
    btn_choose_file: 'Choose File',
    status_uploading_image: 'Uploading image...',
    modal_request_featured_label: 'Pin this post on the homepage (Platinum benefit)',
    btn_cancel: 'Cancel',
    btn_save_draft: 'Save Draft',
    btn_sending: 'Sending...',
    btn_update_publish: 'Update & Publish',
    btn_publish: 'Publish Post',
    err_fill_company_name: 'Please enter company name',
    err_select_industry: 'Please select industry',
    err_select_scale: 'Please select company size',
    err_image_size: 'Please choose an image file smaller than 2MB.',
    err_fill_tax_code: 'Please enter tax code',
    err_select_city: 'Please select city',
    err_fill_address: 'Please enter address',
    err_fill_description: 'Please enter short description',
    err_fill_rep_name: 'Please enter representative name',
    err_fill_rep_position: 'Please enter representative position',
    err_fill_email: 'Please enter contact email',
    err_fill_phone: 'Please enter phone number',
    err_fill_password: 'Please set a password',
    err_password_min_8: 'Password must be at least 8 characters long',
    register_sidebar_circular_text: 'Voma — EXPAND NETWORK, MAXIMIZE OPPORTUNITIES. GLOBAL CONNECTION, SUSTAINABLE GROWTH.',
    register_sidebar_desc: 'Establish your business, build a reputable profile, and expand your business network across the nation.',
    register_card_title: 'Join Voma',
    step_company: 'Company',
    step_representative: 'Representative',
    step_account: 'Account',
    step_1_title: '1. Register Company Info',
    step_2_title: '2. Representative Info',
    step_3_title: '3. Set Secure Password & Choose Plan',
    placeholder_company_name: 'Example: Vina Tech Joint Stock Company',
    label_website: 'Business Website URL',
    placeholder_website: 'Example: https://vinatech.vn',
    placeholder_industry: 'Select or type industry...',
    placeholder_select_scale: '-- Select Size --',
    scale_under_10: 'Under 10 employees',
    scale_10_50: '10 – 50 employees',
    scale_50_200: '50 – 200 employees',
    scale_200_500: '200 – 500 employees',
    scale_over_500: 'Over 500 employees',
    placeholder_tax_code: '10-digit tax code',
    placeholder_city: 'Select or type city...',
    placeholder_address: 'Example: 45 Ly Thuong Kiet, Hoan Kiem, Hanoi',
    label_zip: 'Postal ZIP Code',
    placeholder_zip: 'Example: 100000',
    placeholder_social: 'facebook.com/company',
    placeholder_short_description: 'Brief introduction to products/services...',
    btn_continue: 'Continue',
    btn_back: 'Go Back',
    placeholder_rep_name: 'Full name of contact person',
    placeholder_rep_position: 'Example: Business Director',
    placeholder_rep_email: 'email@company.com',
    placeholder_rep_phone: 'Mobile phone number',
    placeholder_joining_goal: 'Example: Finding agricultural exporters in Japan',
    label_referral: 'How did you hear about Voma?',
    placeholder_referral: '-- Select Referral Channel --',
    label_login_email: 'Login Email (Username)',
    login_email_help_text: 'Voma uses the business email from Step 2 as your login username.',
    label_setup_password: 'Create Password',
    placeholder_setup_password: 'Password must be at least 8 characters',
    label_choose_tier: 'Choose Membership Tier',
    btn_register: 'Register Now',
    btn_registering: 'Registering...',
    register_success_title: 'Registration Successful!',
    register_success_desc: (name, email) => `Business profile for ${name} has been saved and is awaiting admin approval. We will contact you soon at ${email}.`,
    btn_back_home: 'Back to Home',
    status_approved: 'Approved',
    status_rejected: 'Rejected',
    status_draft: 'Draft',
    status_pending: 'Pending'
  },
  zh: {
    flag: '🇨🇳',
    label: 'ZH',
    sb_sub: '会员管理',
    search_placeholder: '搜索...',
    menu_manage: '管理',
    menu_dashboard: '总览',
    menu_members: '会员',
    menu_posts: '文章',
    menu_register: '注册',
    menu_admin: '审核会员',
    menu_ai: 'AI助手',
    menu_system: '系统',
    menu_settings: 'AI设置',
    lang_label: '语言',
    stat_total_members: '总会员数',
    stat_active: '活跃',
    stat_pending: '待审核',
    stat_need_action: '需处理',
    stat_posts: '本月文章',
    stat_published: '已发布',
    stat_events: '即将举办',
    stat_this_month: '本月',
    section_new_members: '新注册会员',
    section_pending_posts: '待审文章',
    btn_add: '新增',
    notify_lang_switch: (n) => `已切换到${n}`,
    menu_directory: '全部名录',
    menu_tiers: '会员权益',
    menu_marketplace: '市场交易',
    menu_opportunities: '商业机会',
    menu_national_feeds: '全国看板',
    menu_events: '活动机会',
    menu_guide: '使用指南',
    menu_login: '登录',
    menu_logout: '退出',
    menu_welcome: '欢迎',
    hero_badge: '越南第一的企业对接平台',
    hero_title: '连接企业，携手共赢可持续发展',
    hero_desc: 'Voma是领先企业之间值得信赖的桥梁。快速搜索贸易伙伴，分享共同投资机会，并使用24/7智能AI业务助手。',
    hero_btn_register: '立即加入（免费）',
    hero_btn_explore: '探索会员',
    hero_realtime: '实时对接越南企业',
    stat_active_members: '活跃会员',
    stat_verified_companies: '已核验企业',
    stat_shared_opportunities: '共享商机',
    stat_new_connections: '定期发布的商业对接',
    stat_diverse_companies: '多元化行业',
    stat_industries: '科技、制造、零售',
    stat_trade_events: '贸易活动',
    stat_annual_meetings: '年度贸易推介会议',
    services_badge: '核心服务',
    services_title: 'B2B智能对接数字解决方案',
    services_desc: 'Voma提供全面的数字化基础架构，帮助您进行贸易、发现合作伙伴并利用AI分析。',
    service_1_title: '会员对接',
    service_1_desc: '与注册会员互动，安全地接触已验证的法人实体企业。',
    service_2_title: '商机看板',
    service_2_desc: '寻找潜在的贸易伙伴，搜索项目需求，并探索投资机会。',
    service_3_title: '智能AI助手',
    service_3_desc: '从我们的AI业务顾问那里获得即时答复，提供自动匹配的合作伙伴推荐。',
    service_4_title: '市场分析',
    service_4_desc: '利用智能AI监控市场趋势并总结行业贸易洞察。',
    featured_projects_title: '热门对接项目',
    featured_projects_desc: '会员发布的优秀贸易和商业机会',
    btn_view_all_posts: '查看全部看板',
    featured_members_title: '优秀会员',
    featured_members_desc: '推荐合作的杰出会员企业',
    btn_view_all_members: '查看会员名录',
    events_section_title: '商务交流与对接活动',
    events_section_desc: '贸易推介、商业论坛和线下对接会',
    btn_view_all_events: '查看全部活动',
    pricing_section_title: '选择合适的会员等级',
    pricing_section_desc: '升级您的会员级别，接触更庞大的合作伙伴数据库，发布无限看板并解锁高级AI功能。',
    tier_silver: '银牌',
    tier_gold: '金牌',
    tier_platinum: '白金牌',
    price_free: '免费',
    price_gold: '490万 越南盾 / 年',
    price_platinum: '990万 越南盾 / 年',
    btn_join_now: '立即加入',
    btn_upgrade_now: '立即订阅',
    footer_desc: 'Voma是领先企业之间值得信赖的桥梁。快速寻找合作伙伴，分享投资商机，并实现24/7自动对接。',
    footer_services: '服务',
    footer_support: '支持',
    footer_contact: '联系我们',
    footer_rights: '© 版权所有 保留所有权利',
    label_popular: '热门',
    label_elite: '至尊',
    price_gold_val: '¥1,400',
    price_platinum_val: '¥4,200',
    pricing_per_year: '年',
    silver_feat_1: '基础会员权限',
    silver_feat_2: '标准会员名录展示',
    silver_feat_3: '每月发布最多 3 篇对接信息',
    silver_feat_4: '基础 AI 助手问答服务',
    gold_feat_1: '包含银牌会员的所有权益',
    gold_feat_2: '在优秀名录中优先展示',
    gold_feat_3: '每月发布最多 15 篇对接信息',
    gold_feat_4: '智能 AI 互动对接自动化',
    gold_feat_5: '获取专属优质贸易商机',
    plat_feat_1: '系统最高优先级权限',
    plat_feat_2: '无限制发布贸易对接信息',
    plat_feat_3: '一对一专属合作伙伴匹配服务',
    plat_feat_4: '深度行业 market research reports',
    plat_feat_5: '定制化品牌专属 AI 助手',
    label_desc: '业务描述',
    btn_read_more: '阅读文章',
    btn_read_post: '阅读',
    btn_view_details: '查看详情',
    btn_back_to_feed: '返回看板',
    label_page: '页',
    btn_back_prev: '上一页',
    btn_go_next: '下一页',
    label_show: '显示',
    posts_title: '文章与贸易机会',
    posts_subtitle: '从会员企业获取最新新闻、贸易机会和招聘信息。',
    members_title: '会员名录',
    members_subtitle: '探索Voma网络中值得信赖的会员企业。',
    search_members_placeholder: '按名称、行业、城市搜索...',
    search_posts_placeholder: '搜索文章、合作伙伴...',
    all_tiers: '所有级别',
    all_industries: '所有行业',
    all_members: '所有会员',
    all_types: '所有类型',
    type_offer: '供应 / 提供',
    type_demand: '需求 / 寻求',
    type_cooperate: '合作',
    type_offer_short: '供应',
    type_demand_short: '需求',
    type_cooperate_short: '合作',
    posts_per_page: (count) => `${count} 篇/页`,
    members_per_page: (count) => `${count} 会员`,
    found_members: (count) => `找到 ${count} 个会员`,
    found_posts: (count) => `找到 ${count} 篇文章`,
    loading_posts: '正在加载文章...',
    loading_members: '正在加载会员列表...',
    no_posts_found: '没有找到匹配的广告。',
    no_members_found: '没有找到匹配的会员。',
    featured_members_header: '推荐优秀会员',
    contact_login_required: '登录以显示联系方式',
    login_required_desc: '您需要登录才能查看该企业的直接联系方式。',
    login_now: '立即登录',
    contact_info_label: '联系方式',
    sidebar_author: '发布单位',
    location_default: '越南',
    desc_default: '尚无详细业务描述。',
    date_posted_label: '发布日期',
    category_default: '常规',
    badge_featured: '精选',
    breadcrumb_home: '首页',
    breadcrumb_opps: '商机看板',
    tier_platinum_partner: '白金合作伙伴',
    tier_platinum_members: '白金会员',
    tier_gold_members: '黄金会员',
    tier_silver_members: '白银会员',
    translate_select_lang: '翻译为',
    translate_button: 'AI翻译',
    translate_view_original: '查看原文 (VI)',
    translate_view_original_short: '查看原文',

    // ZH Additions
    loading_latest_opps: '正在加载最新商机...',
    no_approved_opps: '未找到已审核的商机。',
    btn_contact: '联系我们',
    loading_events_list: '正在加载活动...',
    status_upcoming: '即将举行',
    status_ongoing: '进行中',
    status_completed: '已结束',
    status_cancelled: '已取消',
    login_required_location: '登录以查看详细地点。',
    no_upcoming_events: '目前没有即将举行的贸易活动。',
    error_loading_events: '无法加载活动',
    login_required_event_confirm: '请登录以查看具体地点和活动描述。前往登录页面？',
    login_required_feature: '请登录以使用此功能。',
    error_occurred: '发生错误。',
    events_title: '贸易活动与商务对接',
    events_subtitle: '会员企业之间的线下商务交流与对接会。',
    search_events_placeholder: '搜索活动...',
    error_loading_events_prefix: '加载活动列表时出错:',
    no_events_found: '未找到匹配的活动。',
    event_details_title: '贸易活动详情',
    label_event_name: '活动名称',
    label_organizer: '主办单位',
    label_event_date: '活动日期',
    label_max_capacity: '最大容量',
    label_location: '活动地点',
    label_event_description: '详细说明',
    no_event_desc: '该活动没有详细描述。',
    status_interested: '已关注',
    btn_interest: '关注活动',
    btn_close: '关闭',
    capacity_people: (count) => `${count} 人`,
    capacity_unlimited: '不限制',
    confirm_delete_session: '您确定要删除此对话吗？',
    error_ai_call: 'AI调用时出错。',
    error_send_msg: '发送消息失败',
    date_today: '今天',
    date_yesterday: '昨天',
    login_ai_chat_title: '登录以使用AI助手',
    login_ai_chat_desc: 'AI助手功能仅向已登录并审核通过的会员企业开放。请登录您的会员账号。',
    register_new: '注册新账号',
    chat_history_title: '历史对话',
    new_chat_btn_tooltip: '新对话',
    search_chat_placeholder: '搜索对话...',
    loading_chat_history: '正在加载历史对话...',
    no_chat_history: '没有对话记录。',
    new_chat_session_title: '新对话',
    delete_chat_tooltip: '删除对话',
    label_topics: '主题',
    topic_business: '业务',
    topic_investment: '投资',
    topic_connection: '对接',
    ai_assistant_title: 'AI智能助手',
    status_online: '在线',
    loading_messages: '正在加载消息...',
    ai_welcome_1: '您好！我是Voma的企业分析AI助手。',
    ai_welcome_2: '我已接入会员企业的能力资料库，可协助您查询资质、商机及活动。您今天需要分析哪个领域？',
    ai_suggestion_1_lbl: 'B2B市场分析',
    ai_suggestion_1_val: '分析2026年B2B企业发展现状',
    ai_suggestion_2_lbl: '寻找技术伙伴',
    ai_suggestion_2_val: '在IT行业寻找合作伙伴',
    ai_suggestion_3_lbl: '商务活动',
    ai_suggestion_3_val: '列出即将举行的对接活动',
    ai_thinking: 'AI助手正在思考...',
    chat_input_placeholder: '输入您的消息...',
    chat_help_tip: '按 Enter 发送 · Shift+Enter 换行',
    data_retrieval_label: '数据检索',
    ai_config_title: 'AI配置',
    status_label: '状态',
    premium_model_label: (tier) => `高级模型 (${tier} 计划)`,
    system_default_model: '[系统默认]',
    free_model_desc: '当前模型能够跨会员档案和B2B贸易机会进行交叉搜索。',
    upgrade_to_change_models: '升级到金牌/白金牌以自由更换其他AI模型 (OpenAI, Claude, DeepSeek...)',
    suggested_actions_title: '建议的操作',
    suggested_action_1_title: 'B2B对接',
    suggested_action_1_desc: '索取介绍和联系方式',
    suggested_action_2_title: '参加活动',
    suggested_action_2_desc: '促进直接贸易对接',
    suggested_action_3_title: '投资机会',
    suggested_action_3_desc: 'AI助手预测与分析',
    profile_update_success: '企业资料更新成功！',
    upgrade_confirm_msg: (tier) => `您确定要申请升级到 ${tier} 吗？`,
    upgrade_request_success: '升级申请已发送！请等待管理员审核。',
    upgrade_request_fail: '升级申请失败。',
    delete_post_confirm: (title) => `您确定要删除帖子 "${title}" 吗？`,
    delete_post_success: '帖子删除成功！',
    error_load_post: '无法加载帖子详情。',
    alert_enter_title: '请输入帖子标题',
    alert_enter_body: '请输入帖子详细内容',
    alert_enter_contact: '请提供直接联系方式',
    save_draft_success: '草稿保存成功！',
    publish_post_success: '发布成功！正在等待管理员审核。',
    loading_dashboard: '正在加载控制台数据...',
    dashboard_title: '会员控制台',
    tier_expiry_label: '有效期至',
    pending_upgrade_status: (tier) => `等待升级到 ${tier}`,
    manage_account_desc: (name) => `管理会员企业 ${name} 的账户`,
    btn_create_new_post: '发布新商机',
    pending_account_status_title: '账户等待审核',
    pending_account_status_desc: '管理员正在审查您的企业档案。通过后即可使用发布功能 and AI助手。',
    approved_account_status_title: '正式会员',
    approved_account_status_desc: '您的账户已通过审核。您拥有完整的交易权限，并可以使用AI助手。',
    rejected_account_status_title: '资料被退回',
    rejected_account_status_desc: '企业档案未通过审查。请更新您的详细资料。',
    update_profile_title: '更新企业资料',
    label_company_name: '企业名称',
    label_tax_code: '税号',
    label_business_license: '营业执照',
    label_industry: '所属行业',
    label_employee_scale: '人员规模',
    label_address: '详细地址',
    label_city: '所在省市',
    label_social_media: '社交媒体 (主页 / LinkedIn)',
    label_contact_person: '联系人姓名',
    label_contact_position: '联系人职务',
    label_phone_number: '联系电话',
    label_joining_goal: '加入目标',
    label_short_description: '简要描述',
    label_reset_password_desc: '重置密码 (留空则不修改)',
    placeholder_password_min_8: '密码至少8个字符...',
    btn_saving: '正在保存...',
    btn_save_profile: '保存资料',
    upgrade_tier_title: '升级会员级别',
    upgrade_tier_desc: '升级到金牌或白金牌会员以发布无限商机并提高AI性能。',
    upgrade_request_pending_prefix: '升级申请等待管理员审核中',
    btn_upgrade_gold: '升至金牌',
    btn_upgrade_platinum: '升至白金牌',
    posts_stats_title: '发布统计',
    stat_total_posts: '总发布量',
    stat_approved_posts: '已审核',
    stat_total_views: '阅读量',
    my_published_posts_title: '您发布的对接商机',
    no_posts_published: '您尚未发布任何对接商机。',
    btn_edit: '编辑',
    btn_delete: '删除',
    modal_create_post_title: '发布新对接商机',
    modal_edit_post_title: '编辑对接详情',
    modal_post_title_label: '帖子标题',
    modal_post_title_placeholder: '例如：寻找出口坚果供应商...',
    modal_post_type_label: '帖子类型',
    type_find_partner: '寻找合作伙伴',
    type_buy_sell: '寻求买卖',
    type_event_announcement: '活动通知',
    type_recruitment: '企业招聘',
    modal_post_category_label: '所属行业',
    modal_post_category_placeholder: '例如：农业，信息技术...',
    modal_post_tags_label: '标签 (以英文逗号分隔)',
    modal_post_tags_placeholder: '例如：农产品，出口，b2b',
    modal_post_summary_label: '摘要',
    modal_post_summary_placeholder: '用1-2句话简要总结您的需求...',
    modal_post_body_label: '详细内容',
    modal_post_contact_label: '直接联系方式',
    modal_post_contact_placeholder: '例如：email@vinatech.vn | 0901 111 222 (Mr. 德)',
    modal_post_deadline_label: '截止日期',
    modal_post_image_label: '配图',
    modal_post_image_placeholder: '粘贴图片链接或选择文件上传...',
    btn_choose_file: '选择文件',
    status_uploading_image: '正在上传图片...',
    modal_request_featured_label: '请求在首页置顶此贴 (白金特权)',
    btn_cancel: '取消',
    btn_save_draft: '保存草稿',
    btn_sending: '正在发送...',
    btn_update_publish: '更新并发布',
    btn_publish: '立即发布',
    err_fill_company_name: '请填写企业名称',
    err_select_industry: '请选择行业',
    err_select_scale: '请选择企业人数',
    err_image_size: '请选择小于 2MB 的图片文件。',
    err_fill_tax_code: '请填写税号',
    err_select_city: '请选择城市',
    err_fill_address: '请填写地址',
    err_fill_description: '请填写简要业务描述',
    err_fill_rep_name: '请填写代表姓名',
    err_fill_rep_position: '请填写代表职务',
    err_fill_email: '请填写联系邮箱',
    err_fill_phone: '请填写联系电话',
    err_fill_password: '请设置密码',
    err_password_min_8: '密码长度至少8个字符',
    register_sidebar_circular_text: 'Voma — 扩展网络，开拓商机。全球连接，可持续发展。',
    register_sidebar_desc: '入驻Voma，建立信誉档案，并在全国范围内扩展您的商业关系网。',
    register_card_title: '加入Voma',
    step_company: '企业资料',
    step_representative: '代表信息',
    step_account: '账户设置',
    step_1_title: '1. 填写企业资料',
    step_2_title: '2. 填写代表人信息',
    step_3_title: '3. 设置密码及套餐选择',
    placeholder_company_name: '例如：维纳科技股份有限公司',
    label_website: '企业官网链接',
    placeholder_website: '例如：https://vinatech.vn',
    placeholder_industry: '选择或填写所属行业...',
    placeholder_select_scale: '-- 请选择规模 --',
    scale_under_10: '10人以下',
    scale_10_50: '10 – 50人',
    scale_50_200: '50 – 200人',
    scale_200_500: '200 – 500人',
    scale_over_500: '500人以上',
    placeholder_tax_code: '10位企业税号',
    placeholder_city: '选择或填写城市...',
    placeholder_address: '例如：河内市还剑区李常杰路45号',
    label_zip: '邮政编码',
    placeholder_zip: '例如：100000',
    placeholder_social: 'facebook.com/company',
    placeholder_short_description: '产品或服务简要说明...',
    btn_continue: '继续',
    btn_back: '返回',
    placeholder_rep_name: '联系人姓名',
    placeholder_rep_position: '例如：销售总监',
    placeholder_rep_email: 'email@company.com',
    placeholder_rep_phone: '联系手机号',
    placeholder_joining_goal: '例如：寻找将农产品出口到日本的合作伙伴',
    label_referral: '您是通过什么渠道了解到Voma的？',
    placeholder_referral: '-- 选择推荐渠道 --',
    label_login_email: '登录邮箱 (Username)',
    login_email_help_text: 'Voma 使用第二步中的企业电子邮箱作为登录账号。',
    label_setup_password: '设置密码',
    placeholder_setup_password: '密码需至少包含8个字符',
    label_choose_tier: '选择加入的套餐级别',
    btn_register: '立即注册',
    btn_registering: '正在注册...',
    register_success_title: '注册成功！',
    register_success_desc: (name, email) => `${name} 的企业档案已保存，管理员将进行审核。我们将尽快通过邮箱 ${email} 与您联系。`,
    btn_back_home: '返回首页',
    status_approved: '已批准',
    status_rejected: '被拒绝',
    status_draft: '草稿',
    status_pending: '待审核'
  },
  ja: {
    flag: '🇯🇵',
    label: 'JA',
    sb_sub: '会員管理',
    search_placeholder: '検索...',
    menu_manage: '管理',
    menu_dashboard: 'ダッシュボード',
    menu_members: '会員',
    menu_posts: '投稿',
    menu_register: '登録',
    menu_admin: '会員承認',
    menu_ai: 'AIアシスタント',
    menu_system: 'システム',
    menu_settings: 'AI設定',
    lang_label: '言語',
    stat_total_members: '総会員数',
    stat_active: 'アクティブ',
    stat_pending: '承認待ち',
    stat_need_action: '要対応',
    stat_posts: '今月の投稿',
    stat_published: '公開済み',
    stat_events: '今後のイベント',
    stat_this_month: '今月',
    section_new_members: '新規会員',
    section_pending_posts: '承認待ち記事',
    btn_add: '新規追加',
    notify_lang_switch: (n) => `${n}に切り替えました`,
    menu_directory: 'フルディレクトリ',
    menu_tiers: '会員特典',
    menu_marketplace: 'マーケット',
    menu_opportunities: 'ビジネス機会',
    menu_national_feeds: '全国フィード',
    menu_events: 'イベント',
    menu_guide: 'ガイド',
    menu_login: 'ログイン',
    menu_logout: 'ログアウト',
    menu_welcome: 'ようこそ',
    hero_badge: 'ベトナムNo.1ビジネス・マッチング・プラットフォーム',
    hero_title: '企業を繋ぎ、共に持続可能な成長へ',
    hero_desc: 'Vomaは大手企業間の信頼できる架け橋です。ビジネスパートナーを迅速に検索し、共同投資の機会を共有し、24時間年中無休のスマートAIアシスタントにアクセスします。',
    hero_btn_register: '今すぐ参加（無料）',
    hero_btn_explore: '会員を見つける',
    hero_realtime: 'ベトナム企業のリアルタイム・マッチング',
    stat_active_members: 'アクティブ会員',
    stat_verified_companies: '認証済み企業',
    stat_shared_opportunities: '共有案件',
    stat_new_connections: '定期的なマッチングフィード',
    stat_diverse_companies: '多様な業界',
    stat_industries: 'IT、製造、小売',
    stat_trade_events: 'ビジネスイベント',
    stat_annual_meetings: '年次プロモーション会議',
    services_badge: 'コアサービス',
    services_title: 'B2Bマッチングのデジタルソリューション',
    services_desc: 'Vomaは、取引、パートナーの開拓、AI分析の活用を支援する包括的なデジタルインフラを提供します。',
    service_1_title: '会員接続',
    service_1_desc: '登録会員と交流し、認証済みの安全な法人企業にアプローチします。',
    service_2_title: '案件フィード',
    service_2_desc: '潜在的なパートナーを検索し、プロジェクトニーズを確認し、投資機会を探ります。',
    service_3_title: 'スマートAI助手',
    service_3_desc: 'AIアドバイザーから即座に回答を得て、最適なパートナーの自動提案を受けます。',
    service_4_title: '市場分析',
    service_4_desc: 'スマートAIを活用して市場動向を監視し、業界の取引動向を要約します。',
    featured_projects_title: '注目のマッチング案件',
    featured_projects_desc: '会員から共有された優れた取引およびビジネス案件',
    btn_view_all_posts: 'すべてのフィードを表示',
    featured_members_title: '注目の会員',
    featured_members_desc: 'コラボレーションに推奨される優れた会員企業',
    btn_view_all_members: '会員名録を表示',
    events_section_title: 'ネットワーキング＆マッチングイベント',
    events_section_desc: '貿易プロモーション、ビジネスフォーラム、対面式マッチング会議',
    btn_view_all_events: 'すべてのイベントを表示',
    pricing_section_title: '最適なメンバーシッププランを選択',
    pricing_section_desc: 'プランをアップグレードして、より大きなパートナーデータベースにアクセスし、無制限のフィードを公開し、プレミアムAI機能のロックを解除します。',
    tier_silver: 'シルバー',
    tier_gold: 'ゴールド',
    tier_platinum: 'プラチナ',
    price_free: '無料',
    price_gold: '490万 ドン / 年',
    price_platinum: '990万 ドン / 年',
    btn_join_now: '今すぐ登録',
    btn_upgrade_now: '今すぐ申し込む',
    footer_desc: 'Vomaは大手企業間の信頼できる架け橋です。パートナーを素早く見つけ、投資機会を共有し、24時間365日の自動マッチングを接続します。',
    footer_services: 'サービス',
    footer_support: 'サポート',
    footer_contact: 'お問い合わせ',
    footer_rights: '© All rights reserved. 無断転載を禁じます',
    label_popular: '人気',
    label_elite: 'エリート',
    price_gold_val: '¥31,000',
    price_platinum_val: '¥93,000',
    pricing_per_year: '年',
    silver_feat_1: 'ベーシックメンバーシップ権限',
    silver_feat_2: '標準会員ディレクトリ掲載',
    silver_feat_3: '月間最大3件 of posts published',
    silver_feat_4: '標準的なAIアシスタントQ&Aアクセス',
    gold_feat_1: 'シルバープランの全特典を含む',
    gold_feat_2: '注目の会員枠に優先表示',
    gold_feat_3: '月間最大15件 of posts published',
    gold_feat_4: 'スマートAIマッチングの自動化',
    gold_feat_5: '限定プレミアム案件へのアクセス',
    plat_feat_1: 'システム最高の優先アクセス権',
    plat_feat_2: '無制限의取引案件の公開',
    plat_feat_3: '専任パートナーマッチング相談',
    plat_feat_4: '詳細な業界市場調査レポート',
    plat_feat_5: 'カスタムブランド専用AIアシスタント',
    label_desc: '事業内容',
    btn_read_more: '記事を読む',
    btn_read_post: '読む',
    btn_view_details: '詳細を見る',
    btn_back_to_feed: 'フィードに戻る',
    label_page: 'ページ',
    btn_back_prev: '前へ',
    btn_go_next: '次へ',
    label_show: '表示',
    posts_title: '投稿とビジネス機会',
    posts_subtitle: '会員企業からの最新ニュース、貿易機会、採用情報を取得します。',
    members_title: '会員名録',
    members_subtitle: 'Explore trusted member businesses in the Voma network.',
    search_members_placeholder: '名前、業界、都市で検索...',
    search_posts_placeholder: '投稿、パートナーを検索...',
    all_tiers: 'すべての階級',
    all_industries: 'すべての業界',
    all_members: 'すべての会員',
    all_types: 'すべてのタイプ',
    type_offer: '提供',
    type_demand: ' need',
    type_cooperate: '協力',
    type_offer_short: '提供',
    type_demand_short: '需要',
    type_cooperate_short: '協力',
    posts_per_page: (count) => `${count} 記事/ページ`,
    members_per_page: (count) => `${count} 会員`,
    found_members: (count) => `${count} 会員が見つかりました`,
    found_posts: (count) => `${count} 記事が見つかりました`,
    loading_posts: '投稿を読み込んでいます...',
    loading_members: '会員リストを読み込んでいます...',
    no_posts_found: 'フィルターに一致する投稿が見つかりませんでした。',
    no_members_found: 'フィルターに一致する会員が見つかりませんでした。',
    featured_members_header: 'おすすめの注目会員',
    contact_login_required: 'ログインして連絡先を表示',
    login_required_desc: 'このビジネスの直接の連絡先情報を表示するにはログインする必要があります。',
    login_now: '今すぐログイン',
    contact_info_label: '連絡先情報',
    sidebar_author: '投稿元',
    location_default: 'ベトナム',
    desc_default: 'ビジネスの説明はありません。',
    date_posted_label: '投稿日',
    category_default: '一般',
    badge_featured: '注目',
    breadcrumb_home: 'ホーム',
    breadcrumb_opps: 'フィード',
    tier_platinum_partner: 'プラチナパートナー',
    tier_platinum_members: 'プラチナ会員',
    tier_gold_members: 'ゴールド会員',
    tier_silver_members: 'シルバー会員',
    translate_select_lang: '翻訳先',
    translate_button: 'AI翻訳',
    translate_view_original: '原文を表示 (VI)',
    translate_view_original_short: '原文表示',

    // JA Additions
    loading_latest_opps: '最新の取引案件を読み込んでいます...',
    no_approved_opps: '承認された取引案件はありません。',
    btn_contact: '連絡する',
    loading_events_list: 'イベントを読み込んでいます...',
    status_upcoming: '開催予定',
    status_ongoing: '開催中',
    status_completed: '終了',
    status_cancelled: '中止',
    login_required_location: 'ログインすると開催地が表示されます。',
    no_upcoming_events: '現在、開催予定の貿易イベントはありません。',
    error_loading_events: 'イベントの読み込みに失敗しました',
    login_required_event_confirm: 'イベントの開催場所と説明を表示するにはログインが必要です。ログインページに移動しますか？',
    login_required_feature: 'この機能を利用するにはログインが必要です。',
    error_occurred: 'エラーが発生しました。',
    events_title: 'ビジネスマッチング＆接続イベント',
    events_subtitle: '会員企業間での対面式のビジネス交流と直接マッチング。',
    search_events_placeholder: 'イベントを検索...',
    error_loading_events_prefix: 'イベント一覧の読み込みエラー:',
    no_events_found: '一致するイベントが見つかりませんでした。',
    event_details_title: '貿易イベント詳細',
    label_event_name: 'イベント名',
    label_organizer: '主催者',
    label_event_date: '開催日',
    label_max_capacity: '最大定員',
    label_location: '開催場所',
    label_event_description: '詳細説明',
    no_event_desc: 'このイベントの詳細説明はありません。',
    status_interested: '参加検討中',
    btn_interest: 'イベントに関心あり',
    btn_close: '閉じる',
    capacity_people: (count) => `${count} 人`,
    capacity_unlimited: '上限なし',
    confirm_delete_session: 'この対話を削除してもよろしいですか？',
    error_ai_call: 'AIの呼び出し中にエラーが発生しました。',
    error_send_msg: 'メッセージの送信に失敗しました',
    date_today: '今日',
    date_yesterday: '昨日',
    login_ai_chat_title: 'ログインしてAIアシスタントを使用',
    login_ai_chat_desc: 'AIアシスタント機能は、ログインして承認された会員企業のみがご利用いただけます。会員アカウントにログインしてください。',
    register_new: '新規会員登録',
    chat_history_title: 'チャット履歴',
    new_chat_btn_tooltip: '新しい対話',
    search_chat_placeholder: '対話を検索...',
    loading_chat_history: 'チャット履歴を読み込んでいます...',
    no_chat_history: '対話履歴はありません。',
    new_chat_session_title: '新しい対話',
    delete_chat_tooltip: 'チャットを削除',
    label_topics: 'トピック',
    topic_business: 'ビジネス',
    topic_investment: '投資',
    topic_connection: 'マッチング',
    ai_assistant_title: 'AIスマートアシスタント',
    status_online: 'オンライン',
    loading_messages: 'メッセージを読み込んでいます...',
    ai_welcome_1: 'こんにちは！Vomaの企業分析AIアシスタントです。',
    ai_welcome_2: '会員企業の強みや実績データに基づき、プロファイル、取引案件、イベント情報から検索をお手伝いします。本日はどの分野を分析しますか？',
    ai_suggestion_1_lbl: 'B2B市場分析',
    ai_suggestion_1_val: '2026年におけるB2B企業の現状を分析する',
    ai_suggestion_2_lbl: '技術パートナー検索',
    ai_suggestion_2_val: 'IT業界でパートナーを探す',
    ai_suggestion_3_lbl: 'ビジネスマッチング',
    ai_suggestion_3_val: '今後の接続イベント一覧を表示',
    ai_thinking: 'AIアシスタントが考えています...',
    chat_input_placeholder: 'メッセージを入力してください...',
    chat_help_tip: 'Enterで送信 · Shift+Enterで改行',
    data_retrieval_label: 'データ検索',
    ai_config_title: 'AI設定',
    status_label: 'ステータス',
    premium_model_label: (tier) => `プレミアムモデル (${tier} プラン)`,
    system_default_model: '[システムデフォルト]',
    free_model_desc: '現在のモデルは、全会員プロファイルとB2B取引案件のクロス検索が可能です。',
    upgrade_to_change_models: 'ゴールド/プラチナにアップグレードすると、他のAIモデル（OpenAI, Claude, Grok, DeepSeekなど）への自由な切り替えが可能です。',
    suggested_actions_title: '提案されたアクション',
    suggested_action_1_title: 'B2Bマッチング',
    suggested_action_1_desc: '紹介および連絡先の紹介を依頼',
    suggested_action_2_title: 'イベントに参加',
    suggested_action_2_desc: '直接取引マッチングを促進',
    suggested_action_3_title: '投資機会',
    suggested_action_3_desc: 'AIアシスタント予測・分析',
    profile_update_success: '企業情報が正常に更新されました！',
    upgrade_confirm_msg: (tier) => `${tier}プランへのアップグレードを申請しますか？`,
    upgrade_request_success: 'アップグレード申請を送信しました！管理者の承認をお待ちください。',
    upgrade_request_fail: 'アップグレード申請に失敗しました。',
    delete_post_confirm: (title) => `投稿「${title}」を削除してもよろしいですか？`,
    delete_post_success: '投稿が正常に削除されました！',
    error_load_post: '投稿詳細を読み込めませんでした。',
    alert_enter_title: '投稿タイトルを入力してください',
    alert_enter_body: '投稿の詳細内容を入力してください',
    alert_enter_contact: '直接の連絡先情報を入力してください',
    save_draft_success: '下書きが保存されました！',
    publish_post_success: '正常に公開申請されました！管理者の承認をお待ちください。',
    loading_dashboard: 'ダッシュボードデータを読み込んでいます...',
    dashboard_title: '会員ダッシュボード',
    tier_expiry_label: 'プラン期限',
    pending_upgrade_status: (tier) => `${tier}へのアップグレード保留中`,
    manage_account_desc: (name) => `会員企業 ${name} のアカウント管理`,
    btn_create_new_post: '新しい取引案件を投稿',
    pending_account_status_title: 'アカウント承認待ち',
    pending_account_status_desc: '管理者にて企業プロファイルを審査中です。承認後、投稿機能とAIチャットがご利用可能になります。',
    approved_account_status_title: '正式会員',
    approved_account_status_desc: 'アカウントが承認されました。ビジネスマッチング機能およびAIアシスタントのすべての機能をご利用いただけます。',
    rejected_account_status_title: 'プロファイル却下',
    rejected_account_status_desc: '企業情報が要件を満たしていません。詳細プロファイルを再更新してください。',
    update_profile_title: '企業プロファイルの更新',
    label_company_name: '企業名',
    label_tax_code: '税コード',
    label_business_license: '営業許可証',
    label_industry: '業種',
    label_employee_scale: '従業員規模',
    label_address: '詳細住所',
    label_city: '都市 / 省',
    label_social_media: 'ソーシャルメディア (Webサイト / LinkedIn)',
    label_contact_person: '担当者名',
    label_contact_position: '担当者役職',
    label_phone_number: '電話番号',
    label_joining_goal: '参加目標',
    label_short_description: '事業概要',
    label_reset_password_desc: '新しいパスワードを設定 (変更しない場合は空白のまま)',
    placeholder_password_min_8: 'パスワードは8文字以上...',
    btn_saving: '保存中...',
    btn_save_profile: 'プロファイルを保存',
    upgrade_tier_title: '会員ランクのアップグレード',
    upgrade_tier_desc: 'ゴールドまたはプラチナ会員にアップグレードすると、取引案件を無制限に投稿でき、AIパフォーマンスが向上します。',
    upgrade_request_pending_prefix: 'アップグレード申請の管理者承認待ち',
    btn_upgrade_gold: 'ゴールドにアップグレード',
    btn_upgrade_platinum: 'プラチナにアップグレード',
    posts_stats_title: '投稿統計',
    stat_total_posts: '総投稿数',
    stat_approved_posts: '承認済み',
    stat_total_views: '閲覧数',
    my_published_posts_title: '公開済みの取引案件',
    no_posts_published: 'まだ案件を投稿していません。',
    btn_edit: '編集',
    btn_delete: '削除',
    modal_create_post_title: '新規ビジネスマッチングの投稿',
    modal_edit_post_title: '投稿詳細の編集',
    modal_post_title_label: '投稿タイトル',
    modal_post_title_placeholder: '例: カシューナッツ輸出サプライヤーの募集...',
    modal_post_type_label: '投稿タイプ',
    type_find_partner: 'パートナー開拓',
    type_buy_sell: '売り / 買い',
    type_event_announcement: 'イベント告知',
    type_recruitment: '採用情報',
    modal_post_category_label: '業種カテゴリ',
    modal_post_category_placeholder: '例: 農業、ITなど...',
    modal_post_tags_label: 'タグ (カンマ区切り)',
    modal_post_tags_placeholder: '例: 農産物, 輸出, b2b',
    modal_post_summary_label: '概要',
    modal_post_summary_placeholder: 'ご要望の概要を1〜2文で短く要約してください...',
    modal_post_body_label: '案件詳細',
    modal_post_contact_label: '直接の連絡先情報',
    modal_post_contact_placeholder: '例: email@vinatech.vn | 0901 111 222 (Mr. ドゥック)',
    modal_post_deadline_label: '有効期限 (掲載期限)',
    modal_post_image_label: 'カバー画像',
    modal_post_image_placeholder: '画像のURLを貼り付けるか、ファイルを選択...',
    btn_choose_file: 'ファイルを選択',
    status_uploading_image: '画像をアップロード中...',
    modal_request_featured_label: 'ホームページでこの記事をトップに固定する (プラチナ特典)',
    btn_cancel: 'キャンセル',
    btn_save_draft: '下書き保存',
    btn_sending: '送信中...',
    btn_update_publish: '更新して公開',
    btn_publish: '案件を公開',
    err_fill_company_name: '企業名を入力してください',
    err_select_industry: '業種を選択してください',
    err_select_scale: '従業員数を選択してください',
    err_image_size: '2MB未満の画像ファイルを選択してください。',
    err_fill_tax_code: '税コードを入力してください',
    err_select_city: '都市を選択してください',
    err_fill_address: '住所を入力してください',
    err_fill_description: '短い概要を入力してください',
    err_fill_rep_name: '代表者名を入力してください',
    err_fill_rep_position: '代表役職を入力してください',
    err_fill_email: '連絡先メールアドレスを入力してください',
    err_fill_phone: '電話番号を入力してください',
    err_fill_password: 'パスワードを設定してください',
    err_password_min_8: 'パスワードは8文字以上にする必要があります',
    register_sidebar_circular_text: 'Voma — ネットワーク拡大、機会最大化。グローバル接続、持続可能な成長。',
    register_sidebar_desc: '企業登録を行い、信頼できるプロファイルを構築し、全国にビジネスの輪を広げましょう。',
    register_card_title: 'Vomaへ加入する',
    step_company: '企業情報',
    step_representative: '代表者情報',
    step_account: 'アカウント設定',
    step_1_title: '1. 企業情報の登録',
    step_2_title: '2. 代表者情報の登録',
    step_3_title: '3. セキュリティ設定＆プランの選択',
    placeholder_company_name: '例: ビナ・テック株式会社',
    label_website: '企業WebサイトURL',
    placeholder_website: '例: https://vinatech.vn',
    placeholder_industry: '業種を選択または入力...',
    placeholder_select_scale: '-- 規模を選択 --',
    scale_under_10: '10人未満',
    scale_10_50: '10〜50人',
    scale_50_200: '50〜200人',
    scale_200_500: '200〜500人',
    scale_over_500: '500人以上',
    placeholder_tax_code: '10桁の税コード',
    placeholder_city: '都市を選択または入力...',
    placeholder_address: '例: ハノイ市ホアンキエム区リーチォンキェット路45番地',
    label_zip: '郵便番号',
    placeholder_zip: '例: 100000',
    placeholder_social: 'facebook.com/company',
    placeholder_short_description: '製品やサービスの簡単な説明...',
    btn_continue: '次へ',
    btn_back: '戻る',
    placeholder_rep_name: '連絡窓口のフルネーム',
    placeholder_rep_position: '例: 営業責任者',
    placeholder_rep_email: 'email@company.com',
    placeholder_rep_phone: '連絡先携帯番号',
    placeholder_joining_goal: '例: 日本への農産物輸出パートナーの募集',
    label_referral: 'どのようなきっかけでVomaを知りましたか？',
    placeholder_referral: '-- チャンネルを選択 --',
    label_login_email: 'ログインメール (Username)',
    login_email_help_text: 'Voma はステップ2の企業メールアドレスをログインIDとして使用します。',
    label_setup_password: 'パスワードの設定',
    placeholder_setup_password: 'パスワードは8文字以上にする必要があります',
    label_choose_tier: '加入プランの選択',
    btn_register: '今すぐ登録',
    btn_registering: '登録中...',
    register_success_title: '登録完了！',
    register_success_desc: (name, email) => `企業プロファイル「${name}」が保存され、管理者の承認待ちです。まもなくメール「${email}」にてご連絡いたします。`,
    btn_back_home: 'ホームページに戻る',
    status_approved: '承認済み',
    status_rejected: '拒否されました',
    status_draft: '下書き',
    status_pending: '保留中'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('voma_lang') || 'vi';
  });

  const t = (key) => {
    const langObj = LANGS[currentLang] || LANGS.vi;
    const value = langObj[key] || LANGS.vi[key];
    if (typeof value === 'function') return value;
    return value || key;
  };

  const changeLang = (lang) => {
    if (LANGS[lang]) {
      setCurrentLang(lang);
      localStorage.setItem('voma_lang', lang);
    }
  };

  const getLangDetails = () => LANGS[currentLang] || LANGS.vi;

  return (
    <LanguageContext.Provider value={{ currentLang, t, changeLang, getLangDetails, LANGS }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => useContext(LanguageContext);
